return 
{
	["Data"] = {
		[101] = {
			["ActionFuncName"] = "CreateBullet",
			["Desc"] = "",
			["EditDefVal2"] = "1",
			["EditDefVal3"] = "0,0,0",
			["EditDefVal4"] = "0,0,0",
			["EditDesc1"] = "子弹id",
			["EditDesc2"] = "状态id",
			["EditDesc3"] = "坐标偏移",
			["EditDesc4"] = "旋转偏移",
			["EditType1"] = 2,
			["EditType2"] = 2,
			["EditType3"] = 13,
			["EditType4"] = 13,
			["Id"] = 101,
			["Name"] = "创建子弹",
			["USE_TYPE"] = 2,
		},
		[102] = {
			["ActionFuncName"] = "DestoryBullet",
			["Desc"] = "用途：#n 事件触发时销毁当前子弹#n",
			["Id"] = 102,
			["Name"] = "销毁子弹",
			["USE_TYPE"] = 2,
		},
		[103] = {
			["ActionFuncName"] = "DealDamage",
			["Desc"] = "",
			["Id"] = 103,
			["Name"] = "造成伤害",
			["USE_TYPE"] = 2,
		},
		[200] = {
			["ActionFuncName"] = "PlayFX",
			["Desc"] = "",
			["EditDefVal2"] = "0,0,0",
			["EditDefVal3"] = "0,0,0",
			["EditDefVal4"] = "1,1,1",
			["EditDesc1"] = "特效id",
			["EditDesc2"] = "坐标偏移",
			["EditDesc3"] = "旋转偏移",
			["EditDesc4"] = "缩放",
			["EditType1"] = 2,
			["EditType2"] = 13,
			["EditType3"] = 13,
			["EditType4"] = 13,
			["Id"] = 200,
			["Name"] = "播放特效",
			["USE_TYPE"] = 2,
		},
		[300] = {
			["ActionFuncName"] = "RandomOffset",
			["Desc"] = "",
			["EditDesc1"] = "坐标随机偏移幅度",
			["EditDesc2"] = "旋转随机偏移幅度",
			["EditType1"] = 13,
			["EditType2"] = 13,
			["Id"] = 300,
			["Name"] = "起始位置随机偏移",
			["USE_TYPE"] = 2,
		},
	},
}