return 
{
	["Define"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = {
			["C_DIR"] = 2,
			["L_DIR"] = 1,
			["NONE"] = 0,
			["R_DIR"] = 3,
		},
		["1D_BLEND_TREE_ANI_TYPE"] = {
			["NONE"] = 0,
			["TWO_DIR"] = 1,
		},
		["1D_BLEND_TREE_PARAM_TYPE"] = {
			["HorizontalDir"] = 1,
			["NONE"] = 0,
		},
		["1D_BLEND_TREE_TYPE"] = {
			["SLIDE_MOVE"] = 0,
		},
		["ACTION_FREQUENCY"] = {
			["HIGH"] = 2,
			["LOW"] = 0,
			["MID"] = 1,
		},
		["ADHERE_TYPE"] = {
			["NONE"] = 0,
			["TO_ACTOR"] = 2,
			["TO_CAMERA"] = 4,
			["TO_UI"] = 3,
			["TO_WORLD"] = 1,
		},
		["AI_CDT_TYPE"] = {
			["DEFINE"] = 1,
			["FUNC"] = 3,
			["SENSOR"] = 2,
		},
		["AI_MOVE_CDT_TYPE"] = {
			["DISTANCE_TARGET_GT"] = 2,
			["DISTANCE_TARGET_LT"] = 1,
		},
		["AI_MOVE_TYPE"] = {
			["TOWARDS_ENTITY"] = 1,
		},
		["AI_OPERATE"] = {
			["MOVE"] = 2,
			["RANDOM_STATE"] = 1,
		},
		["ASSIGN_OPERATE"] = {
			["ADD_EQUAL"] = 1,
			["DIV_EQUAL"] = 4,
			["EQUAL"] = 0,
			["MUL_EQUAL"] = 3,
			["SUB_EQUAL"] = 2,
		},
		["ATK_DIR"] = {
			["ATK_BACKWARD"] = 2,
			["ATK_FORWARD"] = 0,
			["CENTER"] = 1,
		},
		["ATTACK_BOX_TYPE"] = {
			["AI_TEST_BLOCK"] = 8,
			["AOE"] = 7,
			["AOE_HURT"] = 11,
			["BLOCK"] = 18,
			["CAMERA_OBSTURCT"] = 15,
			["COLLIDER"] = 6,
			["COLLISION_CHECK"] = 17,
			["DODGE"] = 4,
			["DODGE_CHECK"] = 14,
			["GUIDE"] = 10,
			["HIT"] = 3,
			["HURT"] = 5,
			["MOTOR_OBS_ATK"] = 12,
			["NORMAL"] = 1,
			["OUT_PUT_POINT"] = 13,
			["PUSH_BOX"] = 20,
			["PUSH_MONSTER"] = 9,
			["SHADOW_SIZE"] = 16,
			["SKILL_RUN_ATTACK"] = 19,
			["THROW"] = 2,
		},
		["BF_STOP_TYPE"] = {
			["ACTOR"] = 0,
			["ALL"] = 2,
			["BULLET"] = 1,
		},
		["BLEND_TREE_ANI_DIR_TYPE"] = {
			["B_DIR"] = 5,
			["C_DIR"] = 3,
			["F_DIR"] = 1,
			["L_B_DIR"] = 6,
			["L_DIR"] = 2,
			["L_F_DIR"] = 8,
			["NONE"] = 0,
			["R_B_DIR"] = 7,
			["R_DIR"] = 4,
			["R_F_DIR"] = 9,
		},
		["BLEND_TREE_ANI_TYPE"] = {
			["EIGHT_DIR"] = 3,
			["FOUR_DIR"] = 1,
			["NONE"] = 0,
			["SIX_DIR"] = 2,
		},
		["BLEND_TREE_MASK_TYPE"] = {
			["MoveMask"] = 1,
			["无"] = 0,
		},
		["BLEND_TREE_PARAM_TYPE"] = {
			["MoveDir"] = 1,
			["NONE"] = 0,
		},
		["BLEND_TREE_TYPE"] = {
			["COMBAT_MOVE"] = 0,
			["PEACE_MOVE"] = 1,
			["SLIDE_MOVE"] = 2,
		},
		["BOX_HIT_TYPE"] = {
			["HEAVY_SHOCK"] = 3,
			["NO_MOTION"] = 1,
			["SHOCK"] = 2,
		},
		["BOX_SHAPE_TYPE"] = {
			["CUBE"] = 1,
			["CYLINDER"] = 3,
			["SPHERE"] = 2,
		},
		["BOX_TAB_TYPE"] = {
			["BF_STOP"] = 3,
			["BONE_SHAKE"] = 1,
			["CAMERA_SHAKE"] = 4,
			["CAMERA_SHAKE_DIR"] = 5,
			["CAMERA_SHAKE_ROTATION"] = 6,
			["HIT"] = 2,
		},
		["BTN_CTRL_TYPE"] = {
			["DOWN"] = 0,
			["DOWN_KEEP"] = 3,
			["TWICE_DOWN"] = 1,
			["UP"] = 2,
			["UP_KEEP"] = 4,
		},
		["BUFF_REPLACE_TYPE"] = {
			["BY_ID"] = 4,
			["NONE"] = 0,
			["REPLACE"] = 3,
			["STACK"] = 2,
			["TOGHTER"] = 1,
		},
		["BULLET_CAMP_TYPE"] = {
			["INHERIT_CREATOR"] = 1,
			["INHERIT_LOCK_TARGET"] = 2,
		},
		["BULLET_FILTER_TYPE"] = {
			["BULLET_ID"] = 1,
			["FILTER_ID"] = 2,
		},
		["BULLET_FLY_TYPE"] = {
			["ELLIPSE"] = 2,
			["LINE_FLY"] = 1,
			["PARABOLA"] = 3,
			["SELFROTATE"] = 4,
		},
		["BULLET_POSITION_TYPE"] = {
			["CREATOR_SOCKET"] = 1,
			["LAST_BULLET"] = 4,
			["LEVEL_POINT_ID"] = 3,
			["TARGET_SOCKET"] = 2,
		},
		["CAMERA_BLEND_STYLE"] = {
			["CUT"] = 1,
			["EASEIN"] = 3,
			["EASEINOUT"] = 2,
			["EASEOUT"] = 4,
			["HARDIN"] = 5,
			["HARDOUT"] = 6,
			["LINEAR"] = 7,
			["NONE"] = 0,
		},
		["CAMERA_LAYER_TYPE"] = {
			["EFFECT"] = 1,
			["PLAYER"] = 8,
			["SCENE"] = 0,
		},
		["CAMP"] = {
			["ALL"] = 1,
			["BEHELP_MONSTER"] = 19,
			["COLLISION_BALL"] = 20,
			["CONTROL_MONSTER"] = 33,
			["DESTRUCTABLE"] = 9,
			["DESTRUCTABLE_PLAYER_ONLY"] = 11,
			["DUNGEON_MONSTER"] = 18,
			["ENEMY_MONSTER"] = 28,
			["GHOST_MONSTER"] = 14,
			["GHOST_PET"] = 12,
			["HELP_MONSTER"] = 6,
			["MONSTER"] = 5,
			["NEUTRAL_MONSTER"] = 7,
			["NONE"] = 0,
			["OBSERVE"] = 2,
			["PERFORM_MONSTER_A"] = 15,
			["PERFORM_MONSTER_B"] = 16,
			["PET"] = 4,
			["PLAYER"] = 3,
			["SPECIAL_MONSTER"] = 17,
			["SPEC_PET"] = 13,
			["SYSTEM_PET"] = 21,
			["TEAM1_GHOST_PET"] = 29,
			["TEAM1_PET"] = 24,
			["TEAM1_PLAYER"] = 22,
			["TEAM1_SPEC_PET"] = 31,
			["TEAM1_SYS_PET"] = 26,
			["TEAM2_GHOST_PET"] = 30,
			["TEAM2_PET"] = 25,
			["TEAM2_PLAYER"] = 23,
			["TEAM2_SPEC_PET"] = 32,
			["TEAM2_SYS_PET"] = 27,
			["TEMP_CAMP"] = 10,
			["TRAP"] = 8,
		},
		["COMPARE_OPERATE"] = {
			["EQUAL"] = 2,
			["GREATER_EQUAL"] = 4,
			["GREATER_THAN"] = 1,
			["LESS_EQUAL"] = 3,
			["LESS_THAN"] = 0,
		},
		["DAMAGE_BOX_SUBTYPE"] = {
			["BLUDGEONING"] = 0,
			["CUTTING"] = 1,
			["SHOOTING"] = 2,
		},
		["DATA_INPUT_TYPE"] = {
			["BOOL"] = 1,
			["CUSTOM_DROPDOWN_INT"] = 31,
			["CUSTOM_DROPDOWN_STRING"] = 32,
			["ENUM"] = 6,
			["ENUM_DICT"] = 9,
			["ENUM_LIST"] = 8,
			["EXPANDED_ENUM"] = 22,
			["FIXED"] = 11,
			["FIXED_INT"] = 17,
			["FIXED_INT_LIST"] = 18,
			["FIXED_MULTIPLE"] = 16,
			["FIXED_TIME"] = 15,
			["FIXED_VECTOR2"] = 12,
			["FIXED_VECTOR3"] = 13,
			["FIXED_VECTOR4"] = 14,
			["HIT_TYPE"] = 41,
			["INT"] = 2,
			["INT_ENUM"] = 4,
			["INT_LIST"] = 7,
			["RGBA"] = 21,
			["STRING"] = 5,
			["STRING_LIST"] = 20,
			["WAYPOINT"] = 19,
			["WAYPOINT_LIST"] = 33,
		},
		["DESTROY_TYPE"] = {
			["DESTROY_ON_EXIT_FIGHT"] = 6,
			["DESTROY_ON_TIME"] = 1,
			["FOLLOW_ANIM"] = 4,
			["FOLLOW_BUFF"] = 5,
			["FOLLOW_ENTITY"] = 3,
			["FOLLOW_STATE"] = 2,
			["NONE"] = 0,
		},
		["DIE_TYPE"] = {
			["FORCE_REMOVE"] = 7,
			["LIE_BRUN_DIE"] = 4,
			["LIE_DIE"] = 2,
			["LIE_FREEZE_DIE"] = 6,
			["STAND_BURN_DIE"] = 3,
			["STAND_DIE"] = 1,
			["STAND_FREEZE_DIE"] = 5,
		},
		["DIRECTION"] = {
			["BACK"] = 3,
			["FRONT"] = 2,
			["LEFT"] = 4,
			["NONE"] = 1,
			["RIGHT"] = 5,
		},
		["DIRECTION_TAB_TYPE"] = {
			["BACK"] = 1,
			["FRONT"] = 0,
			["LEFT"] = 2,
			["RIGHT"] = 3,
		},
		["DISAPPEAR_TYPE"] = {
			["IGNORE"] = 2,
			["IMMEDIATELY"] = 1,
			["NONE"] = 0,
			["SOFT_DELETE"] = 3,
		},
		["EDIT_ANIM_STATUS"] = {
			["AIATTACK"] = 10,
			["ATTACK"] = 5,
			["BIRTH"] = 1,
			["COLLECT"] = 15,
			["DEAD"] = 13,
			["FORCE"] = 14,
			["HIT"] = 6,
			["IDLE"] = 3,
			["JUMP"] = 7,
			["KNIFEBACK"] = 11,
			["LIE"] = 9,
			["MOVE"] = 4,
			["NULL"] = 0,
			["REVIVE"] = 2,
			["RUSH"] = 8,
			["UNBALANCE"] = 12,
		},
		["EDIT_EQUSINGLE"] = {
			["BIGEQUL"] = 3,
			["BIGGER"] = 0,
			["EQUL"] = 1,
			["LOWEQUL"] = 4,
			["LOWER"] = 2,
		},
		["EDIT_EXIST"] = {
			["EXIST"] = 1,
			["NONE"] = 0,
		},
		["EDIT_SKILL_BTN_NAME"] = {
			["EVADE_SKILL"] = 2,
			["FIRST_SKILL"] = 5,
			["JUMP"] = 4,
			["NORMAL_ATK"] = 1,
			["NULL"] = 0,
			["SECOND_SKILL"] = 6,
			["SPIRIT_PRESSURE"] = 3,
			["THIRD_SKILL"] = 7,
		},
		["EDIT_STATE_ROTATION"] = {
			["IGNORE_JOYSTICK"] = 2,
			["JOYSTICK_SOON"] = 3,
			["JOYSTICK_TARGET"] = 4,
			["NONE"] = 0,
			["TARGET"] = 1,
		},
		["EFFECT_CAMP_TYPE"] = {
			["HERO"] = 2,
			["MONSTER"] = 3,
			["TEAM"] = 1,
		},
		["EFFECT_ROTATION_TYPE"] = {
			["NONE"] = 0,
			["TO_ACTOR"] = 1,
			["TO_CAMERA"] = 3,
			["TO_IGNORE"] = 2,
			["TO_ROTATION"] = 4,
		},
		["ELLIPSE_TYPE"] = {
			["LEFT_ELLIPSE"] = 1,
			["RIGHT_ELLIPSE"] = 2,
		},
		["EMITTER_TRIGGER_TYPE"] = {
			["COLLIDE_CHR"] = 1,
			["COLLIDE_GROUND"] = 3,
			["COLLIDE_WALL"] = 2,
			["LIFETIME_END"] = 4,
			["MOVE_END"] = 5,
		},
		["EMITTER_TYPE"] = {
			["CIRCLE"] = 1,
			["CUSTOM"] = 3,
			["RANDOM"] = 2,
		},
		["FACETPYE"] = {
			["ENEMY"] = 2,
			["INHERIT_BULLET"] = 3,
			["INHERIT_EMITTER"] = 4,
			["SELF"] = 1,
		},
		["FIRE_TYPE"] = {
			["ACTIVE"] = 1,
			["PASSIVE"] = 2,
		},
		["FLY_TRACK_TYPE"] = {
			["ACCELERATION_LINE"] = 11,
			["ATTACH"] = 5,
			["ATTACH_TARGET"] = 6,
			["FOLLOW"] = 13,
			["GUIDANCE"] = 12,
			["LINE"] = 1,
			["LINE_BOOMERANG"] = 9,
			["LOCK_TARGET_PARABOLA"] = 7,
			["PARABOLA"] = 3,
			["STAY"] = 2,
			["STAY_ON_LAND"] = 4,
			["STAY_ROTATION"] = 10,
			["TORNADO"] = 8,
		},
		["FRAME_EVENT_TYPE"] = {
			["1D_BLEND_TREE_ANIM_EVENT"] = 9,
			["AI_CAN_MOVE_EVENT"] = 11,
			["AI_CAN_SET_STATE_EVENT"] = 12,
			["ANIM_EVENT"] = 7,
			["BLEND_TREE_ANIM_EVENT"] = 8,
			["BOX_EVENT"] = 2,
			["BULLET_EVENT"] = 10,
			["CUSTOM_EVENT"] = 1,
			["DISSOLVE_EVENT"] = 5,
			["EFFECT_EVENT"] = 3,
			["SPEED_EVENT"] = 4,
			["WWISE_EVENT"] = 6,
		},
		["FRAME_EVENT_VAILD_TYPE"] = {
			["CAPTURE_MAIN_PLAYER"] = 1,
			["NONE"] = 0,
		},
		["HERO_ABSTRACT_STATE_TYPE"] = {
			["HERO_IDLE"] = 10000,
			["HERO_MOVE"] = 10008,
			["HERO_SKILL1"] = 10001,
			["HERO_SKILL2"] = 10002,
			["HERO_SKILL3"] = 10003,
			["HERO_SKILL_DODGE"] = 10007,
			["HERO_SKILL_IN"] = 10004,
			["HERO_SKILL_OUT"] = 10005,
			["HERO_SKILL_QTE"] = 10006,
		},
		["HIT_BY_TYPE"] = {
			["HARD_HURT"] = 10001,
			["LIE_HURT"] = 10002,
			["NOT_ACTION_HURT"] = 10003,
		},
		["HIT_RESULT_TYPE"] = {
			["DISAPPEAR"] = 3,
			["HURT_DISAPPEAR"] = 2,
			["HURT_NUM_DISAPPEAR"] = 4,
			["HURT_PENETRATE"] = 1,
			["IGNORE"] = 0,
		},
		["HIT_STATE_TYPE"] = {
			["AFTER"] = 3,
			["LEFT"] = 0,
			["MIDDLE"] = 1,
			["RANDOM"] = 4,
			["RIGHT"] = 2,
		},
		["HIT_TYPE"] = {
			["CHARGE"] = 3,
			["MELEE"] = 1,
			["RANGED"] = 2,
		},
		["INTERRUPT_TAB_TYPE"] = {
			["STATE_PLAYEND"] = 1,
		},
		["KNIFE_TYPE"] = {
			["BE_PARRY"] = 0,
			["PARRY"] = 1,
		},
		["LOGIC_TYPE"] = {
			["ART"] = "combat/camera/cameraArt",
			["NORMAL"] = "combat/camera/cameraArtCombat",
		},
		["MOVE_TYPE"] = {
			["FACE_MOVE"] = 3,
			["LOADING_MOVE"] = 1,
			["LOCK_MOVE"] = 2,
			["OBLIQUE_MOVE"] = 4,
		},
		["OBJ_ATTR"] = {
			["Atk"] = 1,
			["Def"] = 2,
			["DodgeEnergy"] = 9,
			["Hp"] = 0,
			["Op"] = 4,
			["SkillBtnClickTime"] = 10,
			["Sp"] = 6,
			["SpeEnergy"] = 7,
			["TeamEnergy"] = 8,
			["UltEnergy"] = 5,
			["WalkSpeed"] = 3,
		},
		["PRODUCEOTHERTYPE"] = {
			["BULLER_COLLIDER_END"] = 4,
			["BULLET_BREAK_OVER"] = 2,
			["BULLET_COLLIDER_DISAPEAR"] = 5,
			["BULLET_HIT"] = 3,
			["BULLET_LIVE"] = 7,
			["EMITTER_OVER"] = 1,
			["LASR_MOUTH_LIFE_END"] = 6,
			["NONE"] = 0,
		},
		["ROLE_TYPE"] = {
			["HERO"] = 1,
			["HERO_MAINCITY"] = 2,
			["MONSTER"] = 3,
			["NONE"] = 0,
			["WEAPON"] = 4,
		},
		["ROTATION_TYPE"] = {
			["INPUT"] = 0,
			["TARGET"] = 1,
		},
		["RUNSTATE"] = {
			["DASH"] = 3,
			["DASH_TURN"] = 4,
			["RUN"] = 2,
			["STOP"] = 0,
			["WALK"] = 1,
		},
		["RUNTYPE"] = {
			["DASH"] = 3,
			["RUN"] = 2,
			["WALK"] = 1,
		},
		["SHOOTING_DIRTYPE"] = {
			["PARALLEL"] = 0,
			["SECTOR"] = 1,
		},
		["SKILL_BTN_SLOT"] = {
			["DODGE_SLOT"] = 1,
			["RELOAD_SLOT"] = 4,
			["SHOOT_SLOT"] = 5,
			["SKILL1_SLOT"] = 2,
			["SKILL2_SLOT"] = 3,
		},
		["SKILL_BTN_TYPE"] = {
			["DODGE"] = 6,
			["HERO1_SKILL2"] = 8,
			["HERO2_SKILL2"] = 9,
			["MOVE"] = 0,
			["NORMAL"] = 1,
			["RELOAD"] = 7,
			["SKILL1"] = 2,
			["SKILL2"] = 3,
			["SOLDIERS_DUEL"] = 10,
			["SWITCH_HERO1"] = 4,
			["SWITCH_HERO2"] = 5,
		},
		["SKILL_JOYSTICK_INPUT_TYPE"] = {
			["DIRECTION_AND_DISTANCE"] = 2,
			["NONE"] = 0,
			["ONLY_DIRECTION"] = 1,
		},
		["SKILL_JOYSTICK_TYPE"] = {
			["CYCLE"] = 2,
			["FAN"] = 4,
			["NONE"] = 0,
			["PIN_POINT"] = 3,
			["STRAIGHT"] = 1,
		},
		["SKILL_TRIGGER_EVENT"] = {
			["DAMAGE_AFTER"] = 4,
			["DAMAGE_FRONT"] = 3,
			["DODGE_SUCCESS"] = 8,
			["GET_DAMAGE_AFTER"] = 6,
			["GET_DAMAGE_FRONT"] = 5,
			["HERO_IN"] = 1,
			["KILL_CHARACTER"] = 9,
			["NONE"] = 0,
			["RE_BULLETS"] = 10,
			["RE_GUNS"] = 2,
			["USE_HERO_SKILL"] = 7,
		},
		["SKILL_TYPE"] = {
			["GEM_SKILL"] = 10,
			["HERO_SKILL"] = 1,
			["HERO_TACTICAL_SKILL"] = 3,
			["MECHANISM_SKILL"] = 2,
			["MOVEMENT_SKILL"] = 4,
			["SOLDIERS_DUEL"] = 9,
			["VEHICLE_PASSIVE_SKILL"] = 7,
			["VEHICLE_UPGRADE_PASSIVE_SKILL"] = 8,
			["WEAPON_BREAK_SKILL"] = 6,
			["WEAPON_STAR_SKILL"] = 5,
		},
		["SOUND_TYPE"] = {
			["ANIMATION"] = 7,
			["BGM"] = 4,
			["DIALOG"] = 6,
			["ENDING"] = 12,
			["FORMATION"] = 13,
			["HURT"] = 2,
			["INTRO"] = 8,
			["MOVE"] = 11,
			["NONE"] = 0,
			["NORMAL"] = 1,
			["OP"] = 14,
			["PPT"] = 10,
			["RESULT"] = 9,
			["SKILL"] = 5,
			["UI"] = 3,
		},
		["STATE_GUIDE_FX"] = {
			["BUTTERFLY"] = 1,
			["RING"] = 2,
		},
		["STATE_HEIGHT_TYPE"] = {
			["LIE"] = 2,
			["STAND"] = 1,
		},
		["STATE_LIMIT_TYPE"] = {
			["CAMERA_STATE"] = 14,
			["CAN_HIT"] = 5,
			["CAN_MOVE"] = 2,
			["CAN_TURN_AROUND"] = 3,
			["CAN_T_DIE"] = 10,
			["CHECK_SWITCH_HERO"] = 7,
			["ENABLE_DODGE_FACE"] = 9,
			["ENABLE_IK"] = 8,
			["HEAD_LOOK_AT"] = 12,
			["LIMIT_AI"] = 4,
			["LIMIT_AID_SKILL"] = 15,
			["LIMIT_HIT_PROTECT"] = 13,
			["LIMIT_SHAKEBONE"] = 11,
			["NOT_BE_PUSH"] = 16,
			["NOT_BULLET_TIME"] = 18,
			["NOT_PUSH"] = 17,
			["USE_ANIM_CURVE"] = 6,
			["USE_ANIM_OFFSET"] = 1,
		},
		["STATE_TYPE"] = {
			["AIATTACK"] = 10,
			["BORN"] = 1,
			["COLLECT"] = 15,
			["DEAD"] = 13,
			["DEFAULT"] = 0,
			["FORCE"] = 14,
			["HIT"] = 6,
			["IDLE"] = 3,
			["JUMP"] = 7,
			["KNIFEBACK"] = 11,
			["LIE"] = 9,
			["MOVE"] = 4,
			["REVIVE"] = 2,
			["RUSH"] = 8,
			["SKILL"] = 5,
			["UNBALANCE"] = 12,
		},
		["STOP_TYPE"] = {
			["NONE"] = 0,
			["STOP_FORCE"] = 2,
			["STOP_ON_SKILL_BREAK"] = 1,
		},
		["TARGET_SECOND_TYPE"] = {
			["MAP_HP"] = 3,
			["MAX_DISTANCE"] = 1,
			["MIN_DISTANCE"] = 0,
			["MIN_HP"] = 2,
			["RANDOM"] = 4,
		},
		["TRACK_TYPE"] = {
			["1D_BLEND_TREE_ANIM_TRACK"] = 9,
			["AI_CAN_MOVE_TRACK"] = 11,
			["AI_CAN_SET_STATE_TRACK"] = 12,
			["ANIM_TRACK"] = 7,
			["BLEND_TREE_ANIM_TRACK"] = 8,
			["BOX_TRACK"] = 2,
			["BULLET_LIFETIME_TRACK"] = 13,
			["BULLET_TRACK"] = 10,
			["CUSTOM_TRACK"] = 1,
			["DISSOLVE_TRACK"] = 5,
			["EFFECT_TRACK"] = 3,
			["SPEED_TRACK"] = 4,
			["WWISE_TRACK"] = 6,
		},
		["TRIGGER_EFFECTIVE_TYPE"] = {
			["BOSS"] = 3,
			["ELITE"] = 2,
			["ENTOURAGE"] = 4,
			["NONE"] = 0,
			["NORMAL"] = 1,
		},
		["USE_TYPE"] = {
			["ALL"] = 3,
			["LOGIC"] = 2,
			["SHOW"] = 1,
		},
		["VALUE_TYPE"] = {
			["BOOL"] = 1,
			["FLOAT"] = 3,
			["INT"] = 2,
			["TABLE"] = 4,
		},
		["WEAP_ABSTRACT_STATE_TYPE"] = {
			["WEAP_RELOAD"] = 11002,
			["WEAP_SKILL1"] = 11001,
		},
	},
	["ENUM_CN2ID"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = {
			["中动画"] = 2,
			["右动画"] = 3,
			["左动画"] = 1,
			["无"] = 0,
		},
		["1D_BLEND_TREE_ANI_TYPE"] = {
			["2方向"] = 1,
			["无"] = 0,
		},
		["1D_BLEND_TREE_PARAM_TYPE"] = {
			["左右方向"] = 1,
			["无"] = 0,
		},
		["1D_BLEND_TREE_TYPE"] = {
			["滑铲移动"] = 0,
		},
		["ACTION_FREQUENCY"] = {
			["中"] = 1,
			["低"] = 0,
			["高"] = 2,
		},
		["ADHERE_TYPE"] = {
			["UI"] = 3,
			["世界"] = 1,
			["无"] = 0,
			["角色"] = 2,
			["镜头"] = 4,
		},
		["AI_CDT_TYPE"] = {
			["内部定义"] = 1,
			["外部监听"] = 2,
			["方法调用"] = 3,
		},
		["AI_MOVE_CDT_TYPE"] = {
			["与目标距离大于"] = 2,
			["与目标距离小于"] = 1,
		},
		["AI_MOVE_TYPE"] = {
			["朝向目标"] = 1,
		},
		["AI_OPERATE"] = {
			["移动"] = 2,
			["随机转状态"] = 1,
		},
		["ASSIGN_OPERATE"] = {
			["乘等"] = 3,
			["减等"] = 2,
			["加等"] = 1,
			["等于"] = 0,
			["除等"] = 4,
		},
		["ATK_DIR"] = {
			["中心点攻击"] = 1,
			["攻击者朝向"] = 0,
			["攻击者背向"] = 2,
		},
		["ATTACK_BOX_TYPE"] = {
			["AI碰撞检测盒"] = 8,
			["AOE受击盒"] = 11,
			["AOE盒"] = 7,
			["受击盒"] = 5,
			["导出挂点"] = 13,
			["引导盒"] = 10,
			["技能持续攻击盒"] = 19,
			["投掷盒"] = 2,
			["推怪盒"] = 9,
			["推箱盒"] = 20,
			["摩托障碍物攻击盒"] = 12,
			["攻击盒"] = 1,
			["格挡盒"] = 18,
			["特殊命中"] = 3,
			["碰撞检测盒"] = 17,
			["碰撞盒"] = 6,
			["视线遮挡胶囊体"] = 15,
			["闪避检测盒"] = 14,
			["闪避盒"] = 4,
			["阴影大小"] = 16,
		},
		["BF_STOP_TYPE"] = {
			["子弹顿帧"] = 1,
			["角色和子弹顿帧"] = 2,
			["角色顿帧"] = 0,
		},
		["BLEND_TREE_ANI_DIR_TYPE"] = {
			["中动画"] = 3,
			["前动画"] = 1,
			["右前动画"] = 9,
			["右动画"] = 4,
			["右后动画"] = 7,
			["后动画"] = 5,
			["左前动画"] = 8,
			["左动画"] = 2,
			["左后动画"] = 6,
			["无"] = 0,
		},
		["BLEND_TREE_ANI_TYPE"] = {
			["4方向"] = 1,
			["6方向"] = 2,
			["8方向"] = 3,
			["无"] = 0,
		},
		["BLEND_TREE_MASK_TYPE"] = {
			["无"] = 0,
			["移动"] = 1,
		},
		["BLEND_TREE_PARAM_TYPE"] = {
			["无"] = 0,
			["移动方向"] = 1,
		},
		["BLEND_TREE_TYPE"] = {
			["休闲移动"] = 1,
			["战斗移动"] = 0,
			["滑铲移动"] = 2,
		},
		["BOX_HIT_TYPE"] = {
			["大硬直"] = 3,
			["无动作受击"] = 1,
			["硬直"] = 2,
		},
		["BOX_SHAPE_TYPE"] = {
			["圆柱"] = 3,
			["球形"] = 2,
			["矩形"] = 1,
		},
		["BOX_TAB_TYPE"] = {
			["受击配置"] = 2,
			["震屏方向配置"] = 5,
			["震屏旋转配置"] = 6,
			["震屏配置"] = 4,
			["顿帧配置"] = 3,
			["骨骼抖动配置"] = 1,
		},
		["BTN_CTRL_TYPE"] = {
			["2次按下按键"] = 1,
			["按下按键"] = 0,
			["按住按键"] = 3,
			["松开按键"] = 2,
			["松开某键状态"] = 4,
		},
		["BUFF_REPLACE_TYPE"] = {
			["互斥"] = 4,
			["共存"] = 1,
			["叠加"] = 2,
			["无"] = 0,
			["顶掉"] = 3,
		},
		["BULLET_CAMP_TYPE"] = {
			["继承创建者"] = 1,
			["继承锁定目标"] = 2,
		},
		["BULLET_FILTER_TYPE"] = {
			["固定"] = 1,
			["按表格筛选"] = 2,
		},
		["BULLET_FLY_TYPE"] = {
			["抛物线"] = 3,
			["椭圆形轨迹"] = 2,
			["直线飞行"] = 1,
			["自转"] = 4,
		},
		["BULLET_POSITION_TYPE"] = {
			["上一个子弹结束"] = 4,
			["关卡目标点id"] = 3,
			["生成者挂点"] = 1,
			["锁定目标挂点"] = 2,
		},
		["CAMERA_BLEND_STYLE"] = {
			["无"] = 0,
			["淡入"] = 3,
			["淡入淡出"] = 2,
			["淡入硬出"] = 5,
			["淡出"] = 4,
			["瞬切"] = 1,
			["硬入淡出"] = 6,
			["线性"] = 7,
		},
		["CAMERA_LAYER_TYPE"] = {
			["场景"] = 0,
			["特效"] = 1,
			["角色"] = 8,
		},
		["CAMP"] = {
			["中立怪物"] = 7,
			["仅玩家可攻击"] = 11,
			["全部"] = 1,
			["占坑阵营"] = 10,
			["友善怪物"] = 6,
			["可疗友善怪物"] = 19,
			["可破坏物"] = 9,
			["大秘境词条怪物"] = 18,
			["宠物"] = 4,
			["幽灵宠物"] = 12,
			["幽灵怪物"] = 14,
			["怪物"] = 5,
			["敌对怪物"] = 28,
			["无"] = 0,
			["机关"] = 8,
			["特殊宠物"] = 13,
			["特殊怪物"] = 17,
			["玩家"] = 3,
			["碰撞球"] = 20,
			["系统宠物"] = 21,
			["表演怪物A"] = 15,
			["表演怪物B"] = 16,
			["被魅惑怪物"] = 33,
			["观众"] = 2,
			["队伍1宠物"] = 24,
			["队伍1幽灵宠物"] = 29,
			["队伍1特殊宠物"] = 31,
			["队伍1玩家"] = 22,
			["队伍1系统宠物"] = 26,
			["队伍2宠物"] = 25,
			["队伍2幽灵宠物"] = 30,
			["队伍2特殊宠物"] = 32,
			["队伍2玩家"] = 23,
			["队伍2系统宠物"] = 27,
		},
		["COMPARE_OPERATE"] = {
			["大于"] = 1,
			["大于等于"] = 4,
			["小于"] = 0,
			["小于等于"] = 3,
			["等于"] = 2,
		},
		["DAMAGE_BOX_SUBTYPE"] = {
			["切割"] = 1,
			["射击"] = 2,
			["钝击"] = 0,
		},
		["DATA_INPUT_TYPE"] = {
			["受击类型"] = 41,
			["字符串"] = 5,
			["字符串列表"] = 20,
			["定点三维向量"] = 13,
			["定点二维向量"] = 12,
			["定点倍率"] = 16,
			["定点四维向量"] = 14,
			["定点数"] = 11,
			["定点整数"] = 17,
			["定点整数列表"] = 18,
			["定点时间"] = 15,
			["展开枚举"] = 22,
			["布尔"] = 1,
			["整数"] = 2,
			["整数列表"] = 7,
			["整数枚举"] = 4,
			["枚举"] = 6,
			["枚举列表"] = 8,
			["枚举字典"] = 9,
			["自定义列表字符串"] = 32,
			["自定义列表整数"] = 31,
			["路点"] = 19,
			["路点列表"] = 33,
			["颜色值"] = 21,
		},
		["DESTROY_TYPE"] = {
			["buff结束销毁"] = 5,
			["不销毁"] = 0,
			["动作结束销毁"] = 4,
			["定时销毁"] = 1,
			["实体死亡销毁"] = 3,
			["战斗结束销毁"] = 6,
			["状态结束销毁"] = 2,
		},
		["DIE_TYPE"] = {
			["倒地冰冻死亡"] = 6,
			["倒地死亡"] = 2,
			["倒地燃烧死亡"] = 4,
			["强制移除"] = 7,
			["站立冰冻死亡"] = 5,
			["站立死亡"] = 1,
			["站立燃烧死亡"] = 3,
		},
		["DIRECTION"] = {
			["前"] = 2,
			["右"] = 5,
			["后"] = 3,
			["左"] = 4,
			["无"] = 1,
		},
		["DIRECTION_TAB_TYPE"] = {
			["前"] = 0,
			["右"] = 3,
			["后"] = 1,
			["左"] = 2,
		},
		["DISAPPEAR_TYPE"] = {
			["不销毁"] = 2,
			["无"] = 0,
			["立刻销毁"] = 1,
			["软删"] = 3,
		},
		["EDIT_ANIM_STATUS"] = {
			["AI检测技能"] = 10,
			["出生"] = 1,
			["受击"] = 6,
			["复活"] = 2,
			["失衡弹刀"] = 12,
			["强制"] = 14,
			["待机"] = 3,
			["技能"] = 5,
			["死亡"] = 13,
			["移动"] = 4,
			["缺省"] = 0,
			["被弹刀"] = 11,
			["跳跃"] = 7,
			["躺地"] = 9,
			["采集"] = 15,
			["闪避"] = 8,
		},
		["EDIT_EQUSINGLE"] = {
			["大于"] = 0,
			["大等于"] = 3,
			["小于"] = 2,
			["小等于"] = 4,
			["等于"] = 1,
		},
		["EDIT_EXIST"] = {
			["不存在"] = 0,
			["存在类型"] = 1,
		},
		["EDIT_SKILL_BTN_NAME"] = {
			["FirstSkill"] = 5,
			["SecondSkill"] = 6,
			["ThirdSkill"] = 7,
			["大招"] = 3,
			["普攻"] = 1,
			["缺省"] = 0,
			["跳跃"] = 4,
			["闪避"] = 2,
		},
		["EDIT_STATE_ROTATION"] = {
			["依赖摇杆"] = 0,
			["依赖摇杆(一帧转向)"] = 3,
			["角色朝向(无视摇杆)"] = 2,
			["转向锁定目标"] = 1,
			["转向锁定目标(优先摇杆)"] = 4,
		},
		["EFFECT_CAMP_TYPE"] = {
			["怪物"] = 3,
			["玩家"] = 2,
			["队友"] = 1,
		},
		["EFFECT_ROTATION_TYPE"] = {
			["保持初始化旋转"] = 4,
			["保持相机方向"] = 3,
			["取角色当前面向"] = 1,
			["忽略挂点旋转"] = 2,
			["无"] = 0,
		},
		["ELLIPSE_TYPE"] = {
			["右弧形"] = 2,
			["左弧形"] = 1,
		},
		["EMITTER_TRIGGER_TYPE"] = {
			["命中角色"] = 1,
			["撞地"] = 3,
			["撞墙"] = 2,
			["时间结束销毁"] = 4,
			["移动结束"] = 5,
		},
		["EMITTER_TYPE"] = {
			["圆形"] = 1,
			["自定义位置(时间轴控制)"] = 3,
			["随机范围(时间轴控制)"] = 2,
		},
		["FACETPYE"] = {
			["敌人"] = 2,
			["跟随生成它的发射器位置和旋转"] = 4,
			["跟随生成它的子弹位置和旋转"] = 3,
			["释放者"] = 1,
		},
		["FIRE_TYPE"] = {
			["主动技能"] = 1,
			["被动技能"] = 2,
		},
		["FLY_TRACK_TYPE"] = {
			["制导"] = 12,
			["匀加速直线"] = 11,
			["原地"] = 2,
			["原地旋转"] = 10,
			["原地贴地"] = 4,
			["抛物线"] = 3,
			["直线"] = 1,
			["直线回力标"] = 9,
			["跟随"] = 13,
			["锁定抛物线"] = 7,
			["附着"] = 5,
			["附着锁定目标"] = 6,
			["龙卷风"] = 8,
		},
		["FRAME_EVENT_TYPE"] = {
			["1DBlendTree动画事件"] = 9,
			["AI可切换状态事件"] = 12,
			["AI可移动事件"] = 11,
			["BlendTree动画事件"] = 8,
			["动画事件"] = 7,
			["子弹事件"] = 10,
			["溶解事件"] = 5,
			["特效事件"] = 3,
			["盒子事件"] = 2,
			["自定义帧事件"] = 1,
			["速率事件"] = 4,
			["音效事件"] = 6,
		},
		["FRAME_EVENT_VAILD_TYPE"] = {
			["抓取主玩家"] = 1,
			["无"] = 0,
		},
		["HERO_ABSTRACT_STATE_TYPE"] = {
			["英雄QTE"] = 10006,
			["英雄切换入场"] = 10004,
			["英雄切换离场"] = 10005,
			["英雄待机"] = 10000,
			["英雄技能1"] = 10001,
			["英雄技能2"] = 10002,
			["英雄技能3"] = 10003,
			["英雄移动"] = 10008,
			["英雄闪避"] = 10007,
		},
		["HIT_BY_TYPE"] = {
			["受击瘫痪"] = 10002,
			["无动作受击"] = 10003,
			["重受击"] = 10001,
		},
		["HIT_RESULT_TYPE"] = {
			["伤害且消失"] = 2,
			["伤害且穿透"] = 1,
			["伤害次数消失"] = 4,
			["无视"] = 0,
			["消失"] = 3,
		},
		["HIT_STATE_TYPE"] = {
			["上"] = 3,
			["中"] = 1,
			["右"] = 2,
			["左"] = 0,
			["随机"] = 4,
		},
		["HIT_TYPE"] = {
			["蓄力"] = 3,
			["近战"] = 1,
			["远程"] = 2,
		},
		["INTERRUPT_TAB_TYPE"] = {
			["状态播放完毕"] = 1,
		},
		["KNIFE_TYPE"] = {
			["招架"] = 1,
			["被招架"] = 0,
		},
		["LOGIC_TYPE"] = {
			["美术类"] = "combat/camera/cameraArt",
			["通常类"] = "combat/camera/cameraArtCombat",
		},
		["MOVE_TYPE"] = {
			["斜抛运动"] = 4,
			["落地位移"] = 1,
			["锁定移动"] = 2,
			["面向位移"] = 3,
		},
		["OBJ_ATTR"] = {
			["大招能量"] = 5,
			["技能按钮点击次数"] = 10,
			["攻击"] = 1,
			["机制能量"] = 7,
			["灵压值"] = 6,
			["能量"] = 4,
			["血量"] = 0,
			["行走速度"] = 3,
			["闪避能量"] = 9,
			["队伍机制能量"] = 8,
			["防御"] = 2,
		},
		["PRODUCEOTHERTYPE"] = {
			[" 最后一个发射口发射生命周期结束"] = 6,
			["发射器结束"] = 1,
			["子弹击中"] = 3,
			["子弹生成到结束按固定CD持续触发"] = 7,
			["子弹碰撞时间结束"] = 4,
			["子弹碰撞盒消失"] = 5,
			["子弹被中断"] = 2,
			["无"] = 0,
		},
		["ROLE_TYPE"] = {
			["怪物"] = 3,
			["无"] = 0,
			["武器"] = 4,
			["英雄"] = 1,
			["英雄主城"] = 2,
		},
		["ROTATION_TYPE"] = {
			["摇杆"] = 0,
			["转向目标"] = 1,
		},
		["RUNSTATE"] = {
			["冲刺"] = 3,
			["冲刺折返"] = 4,
			["暂停"] = 0,
			["走"] = 1,
			["跑"] = 2,
		},
		["RUNTYPE"] = {
			["冲刺"] = 3,
			["走"] = 1,
			["跑"] = 2,
		},
		["SHOOTING_DIRTYPE"] = {
			["平行"] = 0,
			["扇形"] = 1,
		},
		["SKILL_BTN_SLOT"] = {
			["射击槽位"] = 5,
			["战技槽位"] = 2,
			["绝技槽位"] = 3,
			["装填槽位"] = 4,
			["闪避槽位"] = 1,
		},
		["SKILL_BTN_TYPE"] = {
			["切换后台第一个英雄"] = 4,
			["切换后台第二个英雄"] = 5,
			["后台第一个英雄大招"] = 8,
			["后台第二个英雄大招"] = 9,
			["尖兵对决"] = 10,
			["战技"] = 2,
			["换弹"] = 7,
			["普通攻击"] = 1,
			["移动"] = 0,
			["绝技"] = 3,
			["闪避"] = 6,
		},
		["SKILL_JOYSTICK_INPUT_TYPE"] = {
			["仅方向"] = 1,
			["方向和距离"] = 2,
			["无"] = 0,
		},
		["SKILL_JOYSTICK_TYPE"] = {
			["圆形定点"] = 2,
			["扇形"] = 4,
			["无"] = 0,
			["直线"] = 1,
			["针点形"] = 3,
		},
		["SKILL_TRIGGER_EVENT"] = {
			["使用角色技能"] = 7,
			["切入英雄"] = 1,
			["受到伤害前"] = 5,
			["受到伤害后"] = 6,
			["成功闪避"] = 8,
			["无"] = 0,
			["更换子弹"] = 10,
			["更换枪械"] = 2,
			["造成伤害前"] = 3,
			["造成伤害后"] = 4,
			["造成击杀"] = 9,
		},
		["SKILL_TYPE"] = {
			["宝石特技"] = 10,
			["尖兵对决"] = 9,
			["战技"] = 1,
			["机芯被动技能"] = 4,
			["武器升星被动技能"] = 5,
			["武器突破被动技能"] = 6,
			["绝技"] = 2,
			["角色被动技能"] = 3,
			["载具被动技能"] = 7,
			["载具进阶被动技能"] = 8,
		},
		["SOUND_TYPE"] = {
			["PPT音效"] = 10,
			["上阵"] = 13,
			["出场"] = 14,
			["受击"] = 2,
			["对白"] = 6,
			["技能"] = 5,
			["新手引导"] = 8,
			["无"] = 0,
			["界面"] = 3,
			["移动"] = 11,
			["结算"] = 12,
			["结算页面"] = 9,
			["背景"] = 4,
			["脚本动画"] = 7,
			["通常"] = 1,
		},
		["STATE_GUIDE_FX"] = {
			["光圈"] = 2,
			["蝴蝶"] = 1,
		},
		["STATE_HEIGHT_TYPE"] = {
			["倒地"] = 2,
			["站立"] = 1,
		},
		["STATE_LIMIT_TYPE"] = {
			["不受子弹时间影响"] = 18,
			["不可死亡"] = 10,
			["不被推动"] = 16,
			["不触发受击保护"] = 13,
			["不造成推动"] = 17,
			["使用IK"] = 8,
			["使用动画位移"] = 1,
			["使用曲线"] = 6,
			["使用闪避面向"] = 9,
			["可受击"] = 5,
			["头部转向目标"] = 12,
			["摇杆可移动"] = 2,
			["摇杆可转身"] = 3,
			["检测切换角色"] = 7,
			["禁援助技"] = 15,
			["镜头状态"] = 14,
			["限制AI(可被监视打断)"] = 4,
			["限制骨骼抖动"] = 11,
		},
		["STATE_TYPE"] = {
			["AI检测技能"] = 10,
			["出生"] = 1,
			["受击"] = 6,
			["复活"] = 2,
			["失衡弹刀"] = 12,
			["强制"] = 14,
			["待机"] = 3,
			["技能"] = 5,
			["死亡"] = 13,
			["移动"] = 4,
			["缺省"] = 0,
			["被弹刀"] = 11,
			["跳跃"] = 7,
			["躺地"] = 9,
			["采集"] = 15,
			["闪避"] = 8,
		},
		["STOP_TYPE"] = {
			["技能打断点"] = 1,
			["无"] = 0,
			["被强制打断"] = 2,
		},
		["TARGET_SECOND_TYPE"] = {
			["最大HP"] = 3,
			["最小HP"] = 2,
			["最近距离"] = 0,
			["最远距离"] = 1,
			["随机一个"] = 4,
		},
		["TRACK_TYPE"] = {
			["1DBlendTree动画轨道"] = 9,
			["AI可切换状态轨道"] = 12,
			["AI可移动轨道"] = 11,
			["BlendTree动画轨道"] = 8,
			["动画轨道"] = 7,
			["子弹生命周期轨道"] = 13,
			["子弹轨道"] = 10,
			["溶解轨道"] = 5,
			["特效轨道"] = 3,
			["盒子轨道"] = 2,
			["自定义帧轨道"] = 1,
			["速率轨道"] = 4,
			["音效轨道"] = 6,
		},
		["TRIGGER_EFFECTIVE_TYPE"] = {
			["小怪"] = 1,
			["无"] = 0,
			["精英"] = 2,
			["随从"] = 4,
			["首领"] = 3,
		},
		["USE_TYPE"] = {
			["全部"] = 3,
			["表现"] = 1,
			["逻辑"] = 2,
		},
		["VALUE_TYPE"] = {
			["布尔"] = 1,
			["数据表"] = 4,
			["整数"] = 2,
			["浮点"] = 3,
		},
		["WEAP_ABSTRACT_STATE_TYPE"] = {
			["武器技能1"] = 11001,
			["武器换弹"] = 11002,
		},
	},
	["ENUM_EN2CN"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = {
			["C_DIR"] = "中动画",
			["L_DIR"] = "左动画",
			["NONE"] = "无",
			["R_DIR"] = "右动画",
		},
		["1D_BLEND_TREE_ANI_TYPE"] = {
			["NONE"] = "无",
			["TWO_DIR"] = "2方向",
		},
		["1D_BLEND_TREE_PARAM_TYPE"] = {
			["HorizontalDir"] = "左右方向",
			["NONE"] = "无",
		},
		["1D_BLEND_TREE_TYPE"] = {
			["SLIDE_MOVE"] = "滑铲移动",
		},
		["ACTION_FREQUENCY"] = {
			["HIGH"] = "高",
			["LOW"] = "低",
			["MID"] = "中",
		},
		["ADHERE_TYPE"] = {
			["NONE"] = "无",
			["TO_ACTOR"] = "角色",
			["TO_CAMERA"] = "镜头",
			["TO_UI"] = "UI",
			["TO_WORLD"] = "世界",
		},
		["AI_CDT_TYPE"] = {
			["DEFINE"] = "内部定义",
			["FUNC"] = "方法调用",
			["SENSOR"] = "外部监听",
		},
		["AI_MOVE_CDT_TYPE"] = {
			["DISTANCE_TARGET_GT"] = "与目标距离大于",
			["DISTANCE_TARGET_LT"] = "与目标距离小于",
		},
		["AI_MOVE_TYPE"] = {
			["TOWARDS_ENTITY"] = "朝向目标",
		},
		["AI_OPERATE"] = {
			["MOVE"] = "移动",
			["RANDOM_STATE"] = "随机转状态",
		},
		["ASSIGN_OPERATE"] = {
			["ADD_EQUAL"] = "加等",
			["DIV_EQUAL"] = "除等",
			["EQUAL"] = "等于",
			["MUL_EQUAL"] = "乘等",
			["SUB_EQUAL"] = "减等",
		},
		["ATK_DIR"] = {
			["ATK_BACKWARD"] = "攻击者背向",
			["ATK_FORWARD"] = "攻击者朝向",
			["CENTER"] = "中心点攻击",
		},
		["ATTACK_BOX_TYPE"] = {
			["AI_TEST_BLOCK"] = "AI碰撞检测盒",
			["AOE"] = "AOE盒",
			["AOE_HURT"] = "AOE受击盒",
			["BLOCK"] = "格挡盒",
			["CAMERA_OBSTURCT"] = "视线遮挡胶囊体",
			["COLLIDER"] = "碰撞盒",
			["COLLISION_CHECK"] = "碰撞检测盒",
			["DODGE"] = "闪避盒",
			["DODGE_CHECK"] = "闪避检测盒",
			["GUIDE"] = "引导盒",
			["HIT"] = "特殊命中",
			["HURT"] = "受击盒",
			["MOTOR_OBS_ATK"] = "摩托障碍物攻击盒",
			["NORMAL"] = "攻击盒",
			["OUT_PUT_POINT"] = "导出挂点",
			["PUSH_BOX"] = "推箱盒",
			["PUSH_MONSTER"] = "推怪盒",
			["SHADOW_SIZE"] = "阴影大小",
			["SKILL_RUN_ATTACK"] = "技能持续攻击盒",
			["THROW"] = "投掷盒",
		},
		["BF_STOP_TYPE"] = {
			["ACTOR"] = "角色顿帧",
			["ALL"] = "角色和子弹顿帧",
			["BULLET"] = "子弹顿帧",
		},
		["BLEND_TREE_ANI_DIR_TYPE"] = {
			["B_DIR"] = "后动画",
			["C_DIR"] = "中动画",
			["F_DIR"] = "前动画",
			["L_B_DIR"] = "左后动画",
			["L_DIR"] = "左动画",
			["L_F_DIR"] = "左前动画",
			["NONE"] = "无",
			["R_B_DIR"] = "右后动画",
			["R_DIR"] = "右动画",
			["R_F_DIR"] = "右前动画",
		},
		["BLEND_TREE_ANI_TYPE"] = {
			["EIGHT_DIR"] = "8方向",
			["FOUR_DIR"] = "4方向",
			["NONE"] = "无",
			["SIX_DIR"] = "6方向",
		},
		["BLEND_TREE_MASK_TYPE"] = {
			["MoveMask"] = "移动",
			["无"] = "无",
		},
		["BLEND_TREE_PARAM_TYPE"] = {
			["MoveDir"] = "移动方向",
			["NONE"] = "无",
		},
		["BLEND_TREE_TYPE"] = {
			["COMBAT_MOVE"] = "战斗移动",
			["PEACE_MOVE"] = "休闲移动",
			["SLIDE_MOVE"] = "滑铲移动",
		},
		["BOX_HIT_TYPE"] = {
			["HEAVY_SHOCK"] = "大硬直",
			["NO_MOTION"] = "无动作受击",
			["SHOCK"] = "硬直",
		},
		["BOX_SHAPE_TYPE"] = {
			["CUBE"] = "矩形",
			["CYLINDER"] = "圆柱",
			["SPHERE"] = "球形",
		},
		["BOX_TAB_TYPE"] = {
			["BF_STOP"] = "顿帧配置",
			["BONE_SHAKE"] = "骨骼抖动配置",
			["CAMERA_SHAKE"] = "震屏配置",
			["CAMERA_SHAKE_DIR"] = "震屏方向配置",
			["CAMERA_SHAKE_ROTATION"] = "震屏旋转配置",
			["HIT"] = "受击配置",
		},
		["BTN_CTRL_TYPE"] = {
			["DOWN"] = "按下按键",
			["DOWN_KEEP"] = "按住按键",
			["TWICE_DOWN"] = "2次按下按键",
			["UP"] = "松开按键",
			["UP_KEEP"] = "松开某键状态",
		},
		["BUFF_REPLACE_TYPE"] = {
			["BY_ID"] = "互斥",
			["NONE"] = "无",
			["REPLACE"] = "顶掉",
			["STACK"] = "叠加",
			["TOGHTER"] = "共存",
		},
		["BULLET_CAMP_TYPE"] = {
			["INHERIT_CREATOR"] = "继承创建者",
			["INHERIT_LOCK_TARGET"] = "继承锁定目标",
		},
		["BULLET_FILTER_TYPE"] = {
			["BULLET_ID"] = "固定",
			["FILTER_ID"] = "按表格筛选",
		},
		["BULLET_FLY_TYPE"] = {
			["ELLIPSE"] = "椭圆形轨迹",
			["LINE_FLY"] = "直线飞行",
			["PARABOLA"] = "抛物线",
			["SELFROTATE"] = "自转",
		},
		["BULLET_POSITION_TYPE"] = {
			["CREATOR_SOCKET"] = "生成者挂点",
			["LAST_BULLET"] = "上一个子弹结束",
			["LEVEL_POINT_ID"] = "关卡目标点id",
			["TARGET_SOCKET"] = "锁定目标挂点",
		},
		["CAMERA_BLEND_STYLE"] = {
			["CUT"] = "瞬切",
			["EASEIN"] = "淡入",
			["EASEINOUT"] = "淡入淡出",
			["EASEOUT"] = "淡出",
			["HARDIN"] = "淡入硬出",
			["HARDOUT"] = "硬入淡出",
			["LINEAR"] = "线性",
			["NONE"] = "无",
		},
		["CAMERA_LAYER_TYPE"] = {
			["EFFECT"] = "特效",
			["PLAYER"] = "角色",
			["SCENE"] = "场景",
		},
		["CAMP"] = {
			["ALL"] = "全部",
			["BEHELP_MONSTER"] = "可疗友善怪物",
			["COLLISION_BALL"] = "碰撞球",
			["CONTROL_MONSTER"] = "被魅惑怪物",
			["DESTRUCTABLE"] = "可破坏物",
			["DESTRUCTABLE_PLAYER_ONLY"] = "仅玩家可攻击",
			["DUNGEON_MONSTER"] = "大秘境词条怪物",
			["ENEMY_MONSTER"] = "敌对怪物",
			["GHOST_MONSTER"] = "幽灵怪物",
			["GHOST_PET"] = "幽灵宠物",
			["HELP_MONSTER"] = "友善怪物",
			["MONSTER"] = "怪物",
			["NEUTRAL_MONSTER"] = "中立怪物",
			["NONE"] = "无",
			["OBSERVE"] = "观众",
			["PERFORM_MONSTER_A"] = "表演怪物A",
			["PERFORM_MONSTER_B"] = "表演怪物B",
			["PET"] = "宠物",
			["PLAYER"] = "玩家",
			["SPECIAL_MONSTER"] = "特殊怪物",
			["SPEC_PET"] = "特殊宠物",
			["SYSTEM_PET"] = "系统宠物",
			["TEAM1_GHOST_PET"] = "队伍1幽灵宠物",
			["TEAM1_PET"] = "队伍1宠物",
			["TEAM1_PLAYER"] = "队伍1玩家",
			["TEAM1_SPEC_PET"] = "队伍1特殊宠物",
			["TEAM1_SYS_PET"] = "队伍1系统宠物",
			["TEAM2_GHOST_PET"] = "队伍2幽灵宠物",
			["TEAM2_PET"] = "队伍2宠物",
			["TEAM2_PLAYER"] = "队伍2玩家",
			["TEAM2_SPEC_PET"] = "队伍2特殊宠物",
			["TEAM2_SYS_PET"] = "队伍2系统宠物",
			["TEMP_CAMP"] = "占坑阵营",
			["TRAP"] = "机关",
		},
		["COMPARE_OPERATE"] = {
			["EQUAL"] = "等于",
			["GREATER_EQUAL"] = "大于等于",
			["GREATER_THAN"] = "大于",
			["LESS_EQUAL"] = "小于等于",
			["LESS_THAN"] = "小于",
		},
		["DAMAGE_BOX_SUBTYPE"] = {
			["BLUDGEONING"] = "钝击",
			["CUTTING"] = "切割",
			["SHOOTING"] = "射击",
		},
		["DATA_INPUT_TYPE"] = {
			["BOOL"] = "布尔",
			["CUSTOM_DROPDOWN_INT"] = "自定义列表整数",
			["CUSTOM_DROPDOWN_STRING"] = "自定义列表字符串",
			["ENUM"] = "枚举",
			["ENUM_DICT"] = "枚举字典",
			["ENUM_LIST"] = "枚举列表",
			["EXPANDED_ENUM"] = "展开枚举",
			["FIXED"] = "定点数",
			["FIXED_INT"] = "定点整数",
			["FIXED_INT_LIST"] = "定点整数列表",
			["FIXED_MULTIPLE"] = "定点倍率",
			["FIXED_TIME"] = "定点时间",
			["FIXED_VECTOR2"] = "定点二维向量",
			["FIXED_VECTOR3"] = "定点三维向量",
			["FIXED_VECTOR4"] = "定点四维向量",
			["HIT_TYPE"] = "受击类型",
			["INT"] = "整数",
			["INT_ENUM"] = "整数枚举",
			["INT_LIST"] = "整数列表",
			["RGBA"] = "颜色值",
			["STRING"] = "字符串",
			["STRING_LIST"] = "字符串列表",
			["WAYPOINT"] = "路点",
			["WAYPOINT_LIST"] = "路点列表",
		},
		["DESTROY_TYPE"] = {
			["DESTROY_ON_EXIT_FIGHT"] = "战斗结束销毁",
			["DESTROY_ON_TIME"] = "定时销毁",
			["FOLLOW_ANIM"] = "动作结束销毁",
			["FOLLOW_BUFF"] = "buff结束销毁",
			["FOLLOW_ENTITY"] = "实体死亡销毁",
			["FOLLOW_STATE"] = "状态结束销毁",
			["NONE"] = "不销毁",
		},
		["DIE_TYPE"] = {
			["FORCE_REMOVE"] = "强制移除",
			["LIE_BRUN_DIE"] = "倒地燃烧死亡",
			["LIE_DIE"] = "倒地死亡",
			["LIE_FREEZE_DIE"] = "倒地冰冻死亡",
			["STAND_BURN_DIE"] = "站立燃烧死亡",
			["STAND_DIE"] = "站立死亡",
			["STAND_FREEZE_DIE"] = "站立冰冻死亡",
		},
		["DIRECTION"] = {
			["BACK"] = "后",
			["FRONT"] = "前",
			["LEFT"] = "左",
			["NONE"] = "无",
			["RIGHT"] = "右",
		},
		["DIRECTION_TAB_TYPE"] = {
			["BACK"] = "后",
			["FRONT"] = "前",
			["LEFT"] = "左",
			["RIGHT"] = "右",
		},
		["DISAPPEAR_TYPE"] = {
			["IGNORE"] = "不销毁",
			["IMMEDIATELY"] = "立刻销毁",
			["NONE"] = "无",
			["SOFT_DELETE"] = "软删",
		},
		["EDIT_ANIM_STATUS"] = {
			["AIATTACK"] = "AI检测技能",
			["ATTACK"] = "技能",
			["BIRTH"] = "出生",
			["COLLECT"] = "采集",
			["DEAD"] = "死亡",
			["FORCE"] = "强制",
			["HIT"] = "受击",
			["IDLE"] = "待机",
			["JUMP"] = "跳跃",
			["KNIFEBACK"] = "被弹刀",
			["LIE"] = "躺地",
			["MOVE"] = "移动",
			["NULL"] = "缺省",
			["REVIVE"] = "复活",
			["RUSH"] = "闪避",
			["UNBALANCE"] = "失衡弹刀",
		},
		["EDIT_EQUSINGLE"] = {
			["BIGEQUL"] = "大等于",
			["BIGGER"] = "大于",
			["EQUL"] = "等于",
			["LOWEQUL"] = "小等于",
			["LOWER"] = "小于",
		},
		["EDIT_EXIST"] = {
			["EXIST"] = "存在类型",
			["NONE"] = "不存在",
		},
		["EDIT_SKILL_BTN_NAME"] = {
			["EVADE_SKILL"] = "闪避",
			["FIRST_SKILL"] = "FirstSkill",
			["JUMP"] = "跳跃",
			["NORMAL_ATK"] = "普攻",
			["NULL"] = "缺省",
			["SECOND_SKILL"] = "SecondSkill",
			["SPIRIT_PRESSURE"] = "大招",
			["THIRD_SKILL"] = "ThirdSkill",
		},
		["EDIT_STATE_ROTATION"] = {
			["IGNORE_JOYSTICK"] = "角色朝向(无视摇杆)",
			["JOYSTICK_SOON"] = "依赖摇杆(一帧转向)",
			["JOYSTICK_TARGET"] = "转向锁定目标(优先摇杆)",
			["NONE"] = "依赖摇杆",
			["TARGET"] = "转向锁定目标",
		},
		["EFFECT_CAMP_TYPE"] = {
			["HERO"] = "玩家",
			["MONSTER"] = "怪物",
			["TEAM"] = "队友",
		},
		["EFFECT_ROTATION_TYPE"] = {
			["NONE"] = "无",
			["TO_ACTOR"] = "取角色当前面向",
			["TO_CAMERA"] = "保持相机方向",
			["TO_IGNORE"] = "忽略挂点旋转",
			["TO_ROTATION"] = "保持初始化旋转",
		},
		["ELLIPSE_TYPE"] = {
			["LEFT_ELLIPSE"] = "左弧形",
			["RIGHT_ELLIPSE"] = "右弧形",
		},
		["EMITTER_TRIGGER_TYPE"] = {
			["COLLIDE_CHR"] = "命中角色",
			["COLLIDE_GROUND"] = "撞地",
			["COLLIDE_WALL"] = "撞墙",
			["LIFETIME_END"] = "时间结束销毁",
			["MOVE_END"] = "移动结束",
		},
		["EMITTER_TYPE"] = {
			["CIRCLE"] = "圆形",
			["CUSTOM"] = "自定义位置(时间轴控制)",
			["RANDOM"] = "随机范围(时间轴控制)",
		},
		["FACETPYE"] = {
			["ENEMY"] = "敌人",
			["INHERIT_BULLET"] = "跟随生成它的子弹位置和旋转",
			["INHERIT_EMITTER"] = "跟随生成它的发射器位置和旋转",
			["SELF"] = "释放者",
		},
		["FIRE_TYPE"] = {
			["ACTIVE"] = "主动技能",
			["PASSIVE"] = "被动技能",
		},
		["FLY_TRACK_TYPE"] = {
			["ACCELERATION_LINE"] = "匀加速直线",
			["ATTACH"] = "附着",
			["ATTACH_TARGET"] = "附着锁定目标",
			["FOLLOW"] = "跟随",
			["GUIDANCE"] = "制导",
			["LINE"] = "直线",
			["LINE_BOOMERANG"] = "直线回力标",
			["LOCK_TARGET_PARABOLA"] = "锁定抛物线",
			["PARABOLA"] = "抛物线",
			["STAY"] = "原地",
			["STAY_ON_LAND"] = "原地贴地",
			["STAY_ROTATION"] = "原地旋转",
			["TORNADO"] = "龙卷风",
		},
		["FRAME_EVENT_TYPE"] = {
			["1D_BLEND_TREE_ANIM_EVENT"] = "1DBlendTree动画事件",
			["AI_CAN_MOVE_EVENT"] = "AI可移动事件",
			["AI_CAN_SET_STATE_EVENT"] = "AI可切换状态事件",
			["ANIM_EVENT"] = "动画事件",
			["BLEND_TREE_ANIM_EVENT"] = "BlendTree动画事件",
			["BOX_EVENT"] = "盒子事件",
			["BULLET_EVENT"] = "子弹事件",
			["CUSTOM_EVENT"] = "自定义帧事件",
			["DISSOLVE_EVENT"] = "溶解事件",
			["EFFECT_EVENT"] = "特效事件",
			["SPEED_EVENT"] = "速率事件",
			["WWISE_EVENT"] = "音效事件",
		},
		["FRAME_EVENT_VAILD_TYPE"] = {
			["CAPTURE_MAIN_PLAYER"] = "抓取主玩家",
			["NONE"] = "无",
		},
		["HERO_ABSTRACT_STATE_TYPE"] = {
			["HERO_IDLE"] = "英雄待机",
			["HERO_MOVE"] = "英雄移动",
			["HERO_SKILL1"] = "英雄技能1",
			["HERO_SKILL2"] = "英雄技能2",
			["HERO_SKILL3"] = "英雄技能3",
			["HERO_SKILL_DODGE"] = "英雄闪避",
			["HERO_SKILL_IN"] = "英雄切换入场",
			["HERO_SKILL_OUT"] = "英雄切换离场",
			["HERO_SKILL_QTE"] = "英雄QTE",
		},
		["HIT_BY_TYPE"] = {
			["HARD_HURT"] = "重受击",
			["LIE_HURT"] = "受击瘫痪",
			["NOT_ACTION_HURT"] = "无动作受击",
		},
		["HIT_RESULT_TYPE"] = {
			["DISAPPEAR"] = "消失",
			["HURT_DISAPPEAR"] = "伤害且消失",
			["HURT_NUM_DISAPPEAR"] = "伤害次数消失",
			["HURT_PENETRATE"] = "伤害且穿透",
			["IGNORE"] = "无视",
		},
		["HIT_STATE_TYPE"] = {
			["AFTER"] = "上",
			["LEFT"] = "左",
			["MIDDLE"] = "中",
			["RANDOM"] = "随机",
			["RIGHT"] = "右",
		},
		["HIT_TYPE"] = {
			["CHARGE"] = "蓄力",
			["MELEE"] = "近战",
			["RANGED"] = "远程",
		},
		["INTERRUPT_TAB_TYPE"] = {
			["STATE_PLAYEND"] = "状态播放完毕",
		},
		["KNIFE_TYPE"] = {
			["BE_PARRY"] = "被招架",
			["PARRY"] = "招架",
		},
		["LOGIC_TYPE"] = {
			["ART"] = "美术类",
			["NORMAL"] = "通常类",
		},
		["MOVE_TYPE"] = {
			["FACE_MOVE"] = "面向位移",
			["LOADING_MOVE"] = "落地位移",
			["LOCK_MOVE"] = "锁定移动",
			["OBLIQUE_MOVE"] = "斜抛运动",
		},
		["OBJ_ATTR"] = {
			["Atk"] = "攻击",
			["Def"] = "防御",
			["DodgeEnergy"] = "闪避能量",
			["Hp"] = "血量",
			["Op"] = "能量",
			["SkillBtnClickTime"] = "技能按钮点击次数",
			["Sp"] = "灵压值",
			["SpeEnergy"] = "机制能量",
			["TeamEnergy"] = "队伍机制能量",
			["UltEnergy"] = "大招能量",
			["WalkSpeed"] = "行走速度",
		},
		["PRODUCEOTHERTYPE"] = {
			["BULLER_COLLIDER_END"] = "子弹碰撞时间结束",
			["BULLET_BREAK_OVER"] = "子弹被中断",
			["BULLET_COLLIDER_DISAPEAR"] = "子弹碰撞盒消失",
			["BULLET_HIT"] = "子弹击中",
			["BULLET_LIVE"] = "子弹生成到结束按固定CD持续触发",
			["EMITTER_OVER"] = "发射器结束",
			["LASR_MOUTH_LIFE_END"] = " 最后一个发射口发射生命周期结束",
			["NONE"] = "无",
		},
		["ROLE_TYPE"] = {
			["HERO"] = "英雄",
			["HERO_MAINCITY"] = "英雄主城",
			["MONSTER"] = "怪物",
			["NONE"] = "无",
			["WEAPON"] = "武器",
		},
		["ROTATION_TYPE"] = {
			["INPUT"] = "摇杆",
			["TARGET"] = "转向目标",
		},
		["RUNSTATE"] = {
			["DASH"] = "冲刺",
			["DASH_TURN"] = "冲刺折返",
			["RUN"] = "跑",
			["STOP"] = "暂停",
			["WALK"] = "走",
		},
		["RUNTYPE"] = {
			["DASH"] = "冲刺",
			["RUN"] = "跑",
			["WALK"] = "走",
		},
		["SHOOTING_DIRTYPE"] = {
			["PARALLEL"] = "平行",
			["SECTOR"] = "扇形",
		},
		["SKILL_BTN_SLOT"] = {
			["DODGE_SLOT"] = "闪避槽位",
			["RELOAD_SLOT"] = "装填槽位",
			["SHOOT_SLOT"] = "射击槽位",
			["SKILL1_SLOT"] = "战技槽位",
			["SKILL2_SLOT"] = "绝技槽位",
		},
		["SKILL_BTN_TYPE"] = {
			["DODGE"] = "闪避",
			["HERO1_SKILL2"] = "后台第一个英雄大招",
			["HERO2_SKILL2"] = "后台第二个英雄大招",
			["MOVE"] = "移动",
			["NORMAL"] = "普通攻击",
			["RELOAD"] = "换弹",
			["SKILL1"] = "战技",
			["SKILL2"] = "绝技",
			["SOLDIERS_DUEL"] = "尖兵对决",
			["SWITCH_HERO1"] = "切换后台第一个英雄",
			["SWITCH_HERO2"] = "切换后台第二个英雄",
		},
		["SKILL_JOYSTICK_INPUT_TYPE"] = {
			["DIRECTION_AND_DISTANCE"] = "方向和距离",
			["NONE"] = "无",
			["ONLY_DIRECTION"] = "仅方向",
		},
		["SKILL_JOYSTICK_TYPE"] = {
			["CYCLE"] = "圆形定点",
			["FAN"] = "扇形",
			["NONE"] = "无",
			["PIN_POINT"] = "针点形",
			["STRAIGHT"] = "直线",
		},
		["SKILL_TRIGGER_EVENT"] = {
			["DAMAGE_AFTER"] = "造成伤害后",
			["DAMAGE_FRONT"] = "造成伤害前",
			["DODGE_SUCCESS"] = "成功闪避",
			["GET_DAMAGE_AFTER"] = "受到伤害后",
			["GET_DAMAGE_FRONT"] = "受到伤害前",
			["HERO_IN"] = "切入英雄",
			["KILL_CHARACTER"] = "造成击杀",
			["NONE"] = "无",
			["RE_BULLETS"] = "更换子弹",
			["RE_GUNS"] = "更换枪械",
			["USE_HERO_SKILL"] = "使用角色技能",
		},
		["SKILL_TYPE"] = {
			["GEM_SKILL"] = "宝石特技",
			["HERO_SKILL"] = "战技",
			["HERO_TACTICAL_SKILL"] = "角色被动技能",
			["MECHANISM_SKILL"] = "绝技",
			["MOVEMENT_SKILL"] = "机芯被动技能",
			["SOLDIERS_DUEL"] = "尖兵对决",
			["VEHICLE_PASSIVE_SKILL"] = "载具被动技能",
			["VEHICLE_UPGRADE_PASSIVE_SKILL"] = "载具进阶被动技能",
			["WEAPON_BREAK_SKILL"] = "武器突破被动技能",
			["WEAPON_STAR_SKILL"] = "武器升星被动技能",
		},
		["SOUND_TYPE"] = {
			["ANIMATION"] = "脚本动画",
			["BGM"] = "背景",
			["DIALOG"] = "对白",
			["ENDING"] = "结算",
			["FORMATION"] = "上阵",
			["HURT"] = "受击",
			["INTRO"] = "新手引导",
			["MOVE"] = "移动",
			["NONE"] = "无",
			["NORMAL"] = "通常",
			["OP"] = "出场",
			["PPT"] = "PPT音效",
			["RESULT"] = "结算页面",
			["SKILL"] = "技能",
			["UI"] = "界面",
		},
		["STATE_GUIDE_FX"] = {
			["BUTTERFLY"] = "蝴蝶",
			["RING"] = "光圈",
		},
		["STATE_HEIGHT_TYPE"] = {
			["LIE"] = "倒地",
			["STAND"] = "站立",
		},
		["STATE_LIMIT_TYPE"] = {
			["CAMERA_STATE"] = "镜头状态",
			["CAN_HIT"] = "可受击",
			["CAN_MOVE"] = "摇杆可移动",
			["CAN_TURN_AROUND"] = "摇杆可转身",
			["CAN_T_DIE"] = "不可死亡",
			["CHECK_SWITCH_HERO"] = "检测切换角色",
			["ENABLE_DODGE_FACE"] = "使用闪避面向",
			["ENABLE_IK"] = "使用IK",
			["HEAD_LOOK_AT"] = "头部转向目标",
			["LIMIT_AI"] = "限制AI(可被监视打断)",
			["LIMIT_AID_SKILL"] = "禁援助技",
			["LIMIT_HIT_PROTECT"] = "不触发受击保护",
			["LIMIT_SHAKEBONE"] = "限制骨骼抖动",
			["NOT_BE_PUSH"] = "不被推动",
			["NOT_BULLET_TIME"] = "不受子弹时间影响",
			["NOT_PUSH"] = "不造成推动",
			["USE_ANIM_CURVE"] = "使用曲线",
			["USE_ANIM_OFFSET"] = "使用动画位移",
		},
		["STATE_TYPE"] = {
			["AIATTACK"] = "AI检测技能",
			["BORN"] = "出生",
			["COLLECT"] = "采集",
			["DEAD"] = "死亡",
			["DEFAULT"] = "缺省",
			["FORCE"] = "强制",
			["HIT"] = "受击",
			["IDLE"] = "待机",
			["JUMP"] = "跳跃",
			["KNIFEBACK"] = "被弹刀",
			["LIE"] = "躺地",
			["MOVE"] = "移动",
			["REVIVE"] = "复活",
			["RUSH"] = "闪避",
			["SKILL"] = "技能",
			["UNBALANCE"] = "失衡弹刀",
		},
		["STOP_TYPE"] = {
			["NONE"] = "无",
			["STOP_FORCE"] = "被强制打断",
			["STOP_ON_SKILL_BREAK"] = "技能打断点",
		},
		["TARGET_SECOND_TYPE"] = {
			["MAP_HP"] = "最大HP",
			["MAX_DISTANCE"] = "最远距离",
			["MIN_DISTANCE"] = "最近距离",
			["MIN_HP"] = "最小HP",
			["RANDOM"] = "随机一个",
		},
		["TRACK_TYPE"] = {
			["1D_BLEND_TREE_ANIM_TRACK"] = "1DBlendTree动画轨道",
			["AI_CAN_MOVE_TRACK"] = "AI可移动轨道",
			["AI_CAN_SET_STATE_TRACK"] = "AI可切换状态轨道",
			["ANIM_TRACK"] = "动画轨道",
			["BLEND_TREE_ANIM_TRACK"] = "BlendTree动画轨道",
			["BOX_TRACK"] = "盒子轨道",
			["BULLET_LIFETIME_TRACK"] = "子弹生命周期轨道",
			["BULLET_TRACK"] = "子弹轨道",
			["CUSTOM_TRACK"] = "自定义帧轨道",
			["DISSOLVE_TRACK"] = "溶解轨道",
			["EFFECT_TRACK"] = "特效轨道",
			["SPEED_TRACK"] = "速率轨道",
			["WWISE_TRACK"] = "音效轨道",
		},
		["TRIGGER_EFFECTIVE_TYPE"] = {
			["BOSS"] = "首领",
			["ELITE"] = "精英",
			["ENTOURAGE"] = "随从",
			["NONE"] = "无",
			["NORMAL"] = "小怪",
		},
		["USE_TYPE"] = {
			["ALL"] = "全部",
			["LOGIC"] = "逻辑",
			["SHOW"] = "表现",
		},
		["VALUE_TYPE"] = {
			["BOOL"] = "布尔",
			["FLOAT"] = "浮点",
			["INT"] = "整数",
			["TABLE"] = "数据表",
		},
		["WEAP_ABSTRACT_STATE_TYPE"] = {
			["WEAP_RELOAD"] = "武器换弹",
			["WEAP_SKILL1"] = "武器技能1",
		},
	},
	["ENUM_ID2CN"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = {
			"左动画",
			"中动画",
			"右动画",
			[0] = "无",
		},
		["1D_BLEND_TREE_ANI_TYPE"] = {
			"2方向",
			[0] = "无",
		},
		["1D_BLEND_TREE_PARAM_TYPE"] = {
			"左右方向",
			[0] = "无",
		},
		["1D_BLEND_TREE_TYPE"] = {
			[0] = "滑铲移动",
		},
		["ACTION_FREQUENCY"] = {
			"中",
			"高",
			[0] = "低",
		},
		["ADHERE_TYPE"] = {
			"世界",
			"角色",
			"UI",
			"镜头",
			[0] = "无",
		},
		["AI_CDT_TYPE"] = {
			"内部定义",
			"外部监听",
			"方法调用",
		},
		["AI_MOVE_CDT_TYPE"] = {
			"与目标距离小于",
			"与目标距离大于",
		},
		["AI_MOVE_TYPE"] = {
			"朝向目标",
		},
		["AI_OPERATE"] = {
			"随机转状态",
			"移动",
		},
		["ASSIGN_OPERATE"] = {
			"加等",
			"减等",
			"乘等",
			"除等",
			[0] = "等于",
		},
		["ATK_DIR"] = {
			"中心点攻击",
			"攻击者背向",
			[0] = "攻击者朝向",
		},
		["ATTACK_BOX_TYPE"] = {
			"攻击盒",
			"投掷盒",
			"特殊命中",
			"闪避盒",
			"受击盒",
			"碰撞盒",
			"AOE盒",
			"AI碰撞检测盒",
			"推怪盒",
			"引导盒",
			"AOE受击盒",
			"摩托障碍物攻击盒",
			"导出挂点",
			"闪避检测盒",
			"视线遮挡胶囊体",
			"阴影大小",
			"碰撞检测盒",
			"格挡盒",
			"技能持续攻击盒",
			"推箱盒",
		},
		["BF_STOP_TYPE"] = {
			"子弹顿帧",
			"角色和子弹顿帧",
			[0] = "角色顿帧",
		},
		["BLEND_TREE_ANI_DIR_TYPE"] = {
			"前动画",
			"左动画",
			"中动画",
			"右动画",
			"后动画",
			"左后动画",
			"右后动画",
			"左前动画",
			"右前动画",
			[0] = "无",
		},
		["BLEND_TREE_ANI_TYPE"] = {
			"4方向",
			"6方向",
			"8方向",
			[0] = "无",
		},
		["BLEND_TREE_MASK_TYPE"] = {
			"移动",
			[0] = "无",
		},
		["BLEND_TREE_PARAM_TYPE"] = {
			"移动方向",
			[0] = "无",
		},
		["BLEND_TREE_TYPE"] = {
			"休闲移动",
			"滑铲移动",
			[0] = "战斗移动",
		},
		["BOX_HIT_TYPE"] = {
			"无动作受击",
			"硬直",
			"大硬直",
		},
		["BOX_SHAPE_TYPE"] = {
			"矩形",
			"球形",
			"圆柱",
		},
		["BOX_TAB_TYPE"] = {
			"骨骼抖动配置",
			"受击配置",
			"顿帧配置",
			"震屏配置",
			"震屏方向配置",
			"震屏旋转配置",
		},
		["BTN_CTRL_TYPE"] = {
			"2次按下按键",
			"松开按键",
			"按住按键",
			"松开某键状态",
			[0] = "按下按键",
		},
		["BUFF_REPLACE_TYPE"] = {
			"共存",
			"叠加",
			"顶掉",
			"互斥",
			[0] = "无",
		},
		["BULLET_CAMP_TYPE"] = {
			"继承创建者",
			"继承锁定目标",
		},
		["BULLET_FILTER_TYPE"] = {
			"固定",
			"按表格筛选",
		},
		["BULLET_FLY_TYPE"] = {
			"直线飞行",
			"椭圆形轨迹",
			"抛物线",
			"自转",
		},
		["BULLET_POSITION_TYPE"] = {
			"生成者挂点",
			"锁定目标挂点",
			"关卡目标点id",
			"上一个子弹结束",
		},
		["CAMERA_BLEND_STYLE"] = {
			"瞬切",
			"淡入淡出",
			"淡入",
			"淡出",
			"淡入硬出",
			"硬入淡出",
			"线性",
			[0] = "无",
		},
		["CAMERA_LAYER_TYPE"] = {
			"特效",
			[0] = "场景",
			[8] = "角色",
		},
		["CAMP"] = {
			"全部",
			"观众",
			"玩家",
			"宠物",
			"怪物",
			"友善怪物",
			"中立怪物",
			"机关",
			"可破坏物",
			"占坑阵营",
			"仅玩家可攻击",
			"幽灵宠物",
			"特殊宠物",
			"幽灵怪物",
			"表演怪物A",
			"表演怪物B",
			"特殊怪物",
			"大秘境词条怪物",
			"可疗友善怪物",
			"碰撞球",
			"系统宠物",
			"队伍1玩家",
			"队伍2玩家",
			"队伍1宠物",
			"队伍2宠物",
			"队伍1系统宠物",
			"队伍2系统宠物",
			"敌对怪物",
			"队伍1幽灵宠物",
			"队伍2幽灵宠物",
			"队伍1特殊宠物",
			"队伍2特殊宠物",
			"被魅惑怪物",
			[0] = "无",
		},
		["COMPARE_OPERATE"] = {
			"大于",
			"等于",
			"小于等于",
			"大于等于",
			[0] = "小于",
		},
		["DAMAGE_BOX_SUBTYPE"] = {
			"切割",
			"射击",
			[0] = "钝击",
		},
		["DATA_INPUT_TYPE"] = {
			"布尔",
			"整数",
			[11] = "定点数",
			[12] = "定点二维向量",
			[13] = "定点三维向量",
			[14] = "定点四维向量",
			[15] = "定点时间",
			[16] = "定点倍率",
			[17] = "定点整数",
			[18] = "定点整数列表",
			[19] = "路点",
			[20] = "字符串列表",
			[21] = "颜色值",
			[22] = "展开枚举",
			[31] = "自定义列表整数",
			[32] = "自定义列表字符串",
			[33] = "路点列表",
			[4] = "整数枚举",
			[41] = "受击类型",
			[5] = "字符串",
			[6] = "枚举",
			[7] = "整数列表",
			[8] = "枚举列表",
			[9] = "枚举字典",
		},
		["DESTROY_TYPE"] = {
			"定时销毁",
			"状态结束销毁",
			"实体死亡销毁",
			"动作结束销毁",
			"buff结束销毁",
			"战斗结束销毁",
			[0] = "不销毁",
		},
		["DIE_TYPE"] = {
			"站立死亡",
			"倒地死亡",
			"站立燃烧死亡",
			"倒地燃烧死亡",
			"站立冰冻死亡",
			"倒地冰冻死亡",
			"强制移除",
		},
		["DIRECTION"] = {
			"无",
			"前",
			"后",
			"左",
			"右",
		},
		["DIRECTION_TAB_TYPE"] = {
			"后",
			"左",
			"右",
			[0] = "前",
		},
		["DISAPPEAR_TYPE"] = {
			"立刻销毁",
			"不销毁",
			"软删",
			[0] = "无",
		},
		["EDIT_ANIM_STATUS"] = {
			"出生",
			"复活",
			"待机",
			"移动",
			"技能",
			"受击",
			"跳跃",
			"闪避",
			"躺地",
			"AI检测技能",
			"被弹刀",
			"失衡弹刀",
			"死亡",
			"强制",
			"采集",
			[0] = "缺省",
		},
		["EDIT_EQUSINGLE"] = {
			"等于",
			"小于",
			"大等于",
			"小等于",
			[0] = "大于",
		},
		["EDIT_EXIST"] = {
			"存在类型",
			[0] = "不存在",
		},
		["EDIT_SKILL_BTN_NAME"] = {
			"普攻",
			"闪避",
			"大招",
			"跳跃",
			"FirstSkill",
			"SecondSkill",
			"ThirdSkill",
			[0] = "缺省",
		},
		["EDIT_STATE_ROTATION"] = {
			"转向锁定目标",
			"角色朝向(无视摇杆)",
			"依赖摇杆(一帧转向)",
			"转向锁定目标(优先摇杆)",
			[0] = "依赖摇杆",
		},
		["EFFECT_CAMP_TYPE"] = {
			"队友",
			"玩家",
			"怪物",
		},
		["EFFECT_ROTATION_TYPE"] = {
			"取角色当前面向",
			"忽略挂点旋转",
			"保持相机方向",
			"保持初始化旋转",
			[0] = "无",
		},
		["ELLIPSE_TYPE"] = {
			"左弧形",
			"右弧形",
		},
		["EMITTER_TRIGGER_TYPE"] = {
			"命中角色",
			"撞墙",
			"撞地",
			"时间结束销毁",
			"移动结束",
		},
		["EMITTER_TYPE"] = {
			"圆形",
			"随机范围(时间轴控制)",
			"自定义位置(时间轴控制)",
		},
		["FACETPYE"] = {
			"释放者",
			"敌人",
			"跟随生成它的子弹位置和旋转",
			"跟随生成它的发射器位置和旋转",
		},
		["FIRE_TYPE"] = {
			"主动技能",
			"被动技能",
		},
		["FLY_TRACK_TYPE"] = {
			"直线",
			"原地",
			"抛物线",
			"原地贴地",
			"附着",
			"附着锁定目标",
			"锁定抛物线",
			"龙卷风",
			"直线回力标",
			"原地旋转",
			"匀加速直线",
			"制导",
			"跟随",
		},
		["FRAME_EVENT_TYPE"] = {
			"自定义帧事件",
			"盒子事件",
			"特效事件",
			"速率事件",
			"溶解事件",
			"音效事件",
			"动画事件",
			"BlendTree动画事件",
			"1DBlendTree动画事件",
			"子弹事件",
			"AI可移动事件",
			"AI可切换状态事件",
		},
		["FRAME_EVENT_VAILD_TYPE"] = {
			"抓取主玩家",
			[0] = "无",
		},
		["HERO_ABSTRACT_STATE_TYPE"] = {
			[10000] = "英雄待机",
			[10001] = "英雄技能1",
			[10002] = "英雄技能2",
			[10003] = "英雄技能3",
			[10004] = "英雄切换入场",
			[10005] = "英雄切换离场",
			[10006] = "英雄QTE",
			[10007] = "英雄闪避",
			[10008] = "英雄移动",
		},
		["HIT_BY_TYPE"] = {
			[10001] = "重受击",
			[10002] = "受击瘫痪",
			[10003] = "无动作受击",
		},
		["HIT_RESULT_TYPE"] = {
			"伤害且穿透",
			"伤害且消失",
			"消失",
			"伤害次数消失",
			[0] = "无视",
		},
		["HIT_STATE_TYPE"] = {
			"中",
			"右",
			"上",
			"随机",
			[0] = "左",
		},
		["HIT_TYPE"] = {
			"近战",
			"远程",
			"蓄力",
		},
		["INTERRUPT_TAB_TYPE"] = {
			"状态播放完毕",
		},
		["KNIFE_TYPE"] = {
			"招架",
			[0] = "被招架",
		},
		["LOGIC_TYPE"] = {
			["combat/camera/cameraArt"] = "美术类",
			["combat/camera/cameraArtCombat"] = "通常类",
		},
		["MOVE_TYPE"] = {
			"落地位移",
			"锁定移动",
			"面向位移",
			"斜抛运动",
		},
		["OBJ_ATTR"] = {
			"攻击",
			"防御",
			"行走速度",
			"能量",
			"大招能量",
			"灵压值",
			"机制能量",
			"队伍机制能量",
			"闪避能量",
			"技能按钮点击次数",
			[0] = "血量",
		},
		["PRODUCEOTHERTYPE"] = {
			"发射器结束",
			"子弹被中断",
			"子弹击中",
			"子弹碰撞时间结束",
			"子弹碰撞盒消失",
			" 最后一个发射口发射生命周期结束",
			"子弹生成到结束按固定CD持续触发",
			[0] = "无",
		},
		["ROLE_TYPE"] = {
			"英雄",
			"英雄主城",
			"怪物",
			"武器",
			[0] = "无",
		},
		["ROTATION_TYPE"] = {
			"转向目标",
			[0] = "摇杆",
		},
		["RUNSTATE"] = {
			"走",
			"跑",
			"冲刺",
			"冲刺折返",
			[0] = "暂停",
		},
		["RUNTYPE"] = {
			"走",
			"跑",
			"冲刺",
		},
		["SHOOTING_DIRTYPE"] = {
			"扇形",
			[0] = "平行",
		},
		["SKILL_BTN_SLOT"] = {
			"闪避槽位",
			"战技槽位",
			"绝技槽位",
			"装填槽位",
			"射击槽位",
		},
		["SKILL_BTN_TYPE"] = {
			"普通攻击",
			"战技",
			"绝技",
			"切换后台第一个英雄",
			"切换后台第二个英雄",
			"闪避",
			"换弹",
			"后台第一个英雄大招",
			"后台第二个英雄大招",
			"尖兵对决",
			[0] = "移动",
		},
		["SKILL_JOYSTICK_INPUT_TYPE"] = {
			"仅方向",
			"方向和距离",
			[0] = "无",
		},
		["SKILL_JOYSTICK_TYPE"] = {
			"直线",
			"圆形定点",
			"针点形",
			"扇形",
			[0] = "无",
		},
		["SKILL_TRIGGER_EVENT"] = {
			"切入英雄",
			"更换枪械",
			"造成伤害前",
			"造成伤害后",
			"受到伤害前",
			"受到伤害后",
			"使用角色技能",
			"成功闪避",
			"造成击杀",
			"更换子弹",
			[0] = "无",
		},
		["SKILL_TYPE"] = {
			"战技",
			"绝技",
			"角色被动技能",
			"机芯被动技能",
			"武器升星被动技能",
			"武器突破被动技能",
			"载具被动技能",
			"载具进阶被动技能",
			"尖兵对决",
			"宝石特技",
		},
		["SOUND_TYPE"] = {
			"通常",
			"受击",
			"界面",
			"背景",
			"技能",
			"对白",
			"脚本动画",
			"新手引导",
			"结算页面",
			"PPT音效",
			"移动",
			"结算",
			"上阵",
			"出场",
			[0] = "无",
		},
		["STATE_GUIDE_FX"] = {
			"蝴蝶",
			"光圈",
		},
		["STATE_HEIGHT_TYPE"] = {
			"站立",
			"倒地",
		},
		["STATE_LIMIT_TYPE"] = {
			"使用动画位移",
			"摇杆可移动",
			"摇杆可转身",
			"限制AI(可被监视打断)",
			"可受击",
			"使用曲线",
			"检测切换角色",
			"使用IK",
			"使用闪避面向",
			"不可死亡",
			"限制骨骼抖动",
			"头部转向目标",
			"不触发受击保护",
			"镜头状态",
			"禁援助技",
			"不被推动",
			"不造成推动",
			"不受子弹时间影响",
		},
		["STATE_TYPE"] = {
			"出生",
			"复活",
			"待机",
			"移动",
			"技能",
			"受击",
			"跳跃",
			"闪避",
			"躺地",
			"AI检测技能",
			"被弹刀",
			"失衡弹刀",
			"死亡",
			"强制",
			"采集",
			[0] = "缺省",
		},
		["STOP_TYPE"] = {
			"技能打断点",
			"被强制打断",
			[0] = "无",
		},
		["TARGET_SECOND_TYPE"] = {
			"最远距离",
			"最小HP",
			"最大HP",
			"随机一个",
			[0] = "最近距离",
		},
		["TRACK_TYPE"] = {
			"自定义帧轨道",
			"盒子轨道",
			"特效轨道",
			"速率轨道",
			"溶解轨道",
			"音效轨道",
			"动画轨道",
			"BlendTree动画轨道",
			"1DBlendTree动画轨道",
			"子弹轨道",
			"AI可移动轨道",
			"AI可切换状态轨道",
			"子弹生命周期轨道",
		},
		["TRIGGER_EFFECTIVE_TYPE"] = {
			"小怪",
			"精英",
			"首领",
			"随从",
			[0] = "无",
		},
		["USE_TYPE"] = {
			"表现",
			"逻辑",
			"全部",
		},
		["VALUE_TYPE"] = {
			"布尔",
			"整数",
			"浮点",
			"数据表",
		},
		["WEAP_ABSTRACT_STATE_TYPE"] = {
			[11001] = "武器技能1",
			[11002] = "武器换弹",
		},
	},
	["ENUM_ID2EN"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = {
			"L_DIR",
			"C_DIR",
			"R_DIR",
			[0] = "NONE",
		},
		["1D_BLEND_TREE_ANI_TYPE"] = {
			"TWO_DIR",
			[0] = "NONE",
		},
		["1D_BLEND_TREE_PARAM_TYPE"] = {
			"HorizontalDir",
			[0] = "NONE",
		},
		["1D_BLEND_TREE_TYPE"] = {
			[0] = "SLIDE_MOVE",
		},
		["ACTION_FREQUENCY"] = {
			"MID",
			"HIGH",
			[0] = "LOW",
		},
		["ADHERE_TYPE"] = {
			"TO_WORLD",
			"TO_ACTOR",
			"TO_UI",
			"TO_CAMERA",
			[0] = "NONE",
		},
		["AI_CDT_TYPE"] = {
			"DEFINE",
			"SENSOR",
			"FUNC",
		},
		["AI_MOVE_CDT_TYPE"] = {
			"DISTANCE_TARGET_LT",
			"DISTANCE_TARGET_GT",
		},
		["AI_MOVE_TYPE"] = {
			"TOWARDS_ENTITY",
		},
		["AI_OPERATE"] = {
			"RANDOM_STATE",
			"MOVE",
		},
		["ASSIGN_OPERATE"] = {
			"ADD_EQUAL",
			"SUB_EQUAL",
			"MUL_EQUAL",
			"DIV_EQUAL",
			[0] = "EQUAL",
		},
		["ATK_DIR"] = {
			"CENTER",
			"ATK_BACKWARD",
			[0] = "ATK_FORWARD",
		},
		["ATTACK_BOX_TYPE"] = {
			"NORMAL",
			"THROW",
			"HIT",
			"DODGE",
			"HURT",
			"COLLIDER",
			"AOE",
			"AI_TEST_BLOCK",
			"PUSH_MONSTER",
			"GUIDE",
			"AOE_HURT",
			"MOTOR_OBS_ATK",
			"OUT_PUT_POINT",
			"DODGE_CHECK",
			"CAMERA_OBSTURCT",
			"SHADOW_SIZE",
			"COLLISION_CHECK",
			"BLOCK",
			"SKILL_RUN_ATTACK",
			"PUSH_BOX",
		},
		["BF_STOP_TYPE"] = {
			"BULLET",
			"ALL",
			[0] = "ACTOR",
		},
		["BLEND_TREE_ANI_DIR_TYPE"] = {
			"F_DIR",
			"L_DIR",
			"C_DIR",
			"R_DIR",
			"B_DIR",
			"L_B_DIR",
			"R_B_DIR",
			"L_F_DIR",
			"R_F_DIR",
			[0] = "NONE",
		},
		["BLEND_TREE_ANI_TYPE"] = {
			"FOUR_DIR",
			"SIX_DIR",
			"EIGHT_DIR",
			[0] = "NONE",
		},
		["BLEND_TREE_MASK_TYPE"] = {
			"MoveMask",
			[0] = "无",
		},
		["BLEND_TREE_PARAM_TYPE"] = {
			"MoveDir",
			[0] = "NONE",
		},
		["BLEND_TREE_TYPE"] = {
			"PEACE_MOVE",
			"SLIDE_MOVE",
			[0] = "COMBAT_MOVE",
		},
		["BOX_HIT_TYPE"] = {
			"NO_MOTION",
			"SHOCK",
			"HEAVY_SHOCK",
		},
		["BOX_SHAPE_TYPE"] = {
			"CUBE",
			"SPHERE",
			"CYLINDER",
		},
		["BOX_TAB_TYPE"] = {
			"BONE_SHAKE",
			"HIT",
			"BF_STOP",
			"CAMERA_SHAKE",
			"CAMERA_SHAKE_DIR",
			"CAMERA_SHAKE_ROTATION",
		},
		["BTN_CTRL_TYPE"] = {
			"TWICE_DOWN",
			"UP",
			"DOWN_KEEP",
			"UP_KEEP",
			[0] = "DOWN",
		},
		["BUFF_REPLACE_TYPE"] = {
			"TOGHTER",
			"STACK",
			"REPLACE",
			"BY_ID",
			[0] = "NONE",
		},
		["BULLET_CAMP_TYPE"] = {
			"INHERIT_CREATOR",
			"INHERIT_LOCK_TARGET",
		},
		["BULLET_FILTER_TYPE"] = {
			"BULLET_ID",
			"FILTER_ID",
		},
		["BULLET_FLY_TYPE"] = {
			"LINE_FLY",
			"ELLIPSE",
			"PARABOLA",
			"SELFROTATE",
		},
		["BULLET_POSITION_TYPE"] = {
			"CREATOR_SOCKET",
			"TARGET_SOCKET",
			"LEVEL_POINT_ID",
			"LAST_BULLET",
		},
		["CAMERA_BLEND_STYLE"] = {
			"CUT",
			"EASEINOUT",
			"EASEIN",
			"EASEOUT",
			"HARDIN",
			"HARDOUT",
			"LINEAR",
			[0] = "NONE",
		},
		["CAMERA_LAYER_TYPE"] = {
			"EFFECT",
			[0] = "SCENE",
			[8] = "PLAYER",
		},
		["CAMP"] = {
			"ALL",
			"OBSERVE",
			"PLAYER",
			"PET",
			"MONSTER",
			"HELP_MONSTER",
			"NEUTRAL_MONSTER",
			"TRAP",
			"DESTRUCTABLE",
			"TEMP_CAMP",
			"DESTRUCTABLE_PLAYER_ONLY",
			"GHOST_PET",
			"SPEC_PET",
			"GHOST_MONSTER",
			"PERFORM_MONSTER_A",
			"PERFORM_MONSTER_B",
			"SPECIAL_MONSTER",
			"DUNGEON_MONSTER",
			"BEHELP_MONSTER",
			"COLLISION_BALL",
			"SYSTEM_PET",
			"TEAM1_PLAYER",
			"TEAM2_PLAYER",
			"TEAM1_PET",
			"TEAM2_PET",
			"TEAM1_SYS_PET",
			"TEAM2_SYS_PET",
			"ENEMY_MONSTER",
			"TEAM1_GHOST_PET",
			"TEAM2_GHOST_PET",
			"TEAM1_SPEC_PET",
			"TEAM2_SPEC_PET",
			"CONTROL_MONSTER",
			[0] = "NONE",
		},
		["COMPARE_OPERATE"] = {
			"GREATER_THAN",
			"EQUAL",
			"LESS_EQUAL",
			"GREATER_EQUAL",
			[0] = "LESS_THAN",
		},
		["DAMAGE_BOX_SUBTYPE"] = {
			"CUTTING",
			"SHOOTING",
			[0] = "BLUDGEONING",
		},
		["DATA_INPUT_TYPE"] = {
			"BOOL",
			"INT",
			[11] = "FIXED",
			[12] = "FIXED_VECTOR2",
			[13] = "FIXED_VECTOR3",
			[14] = "FIXED_VECTOR4",
			[15] = "FIXED_TIME",
			[16] = "FIXED_MULTIPLE",
			[17] = "FIXED_INT",
			[18] = "FIXED_INT_LIST",
			[19] = "WAYPOINT",
			[20] = "STRING_LIST",
			[21] = "RGBA",
			[22] = "EXPANDED_ENUM",
			[31] = "CUSTOM_DROPDOWN_INT",
			[32] = "CUSTOM_DROPDOWN_STRING",
			[33] = "WAYPOINT_LIST",
			[4] = "INT_ENUM",
			[41] = "HIT_TYPE",
			[5] = "STRING",
			[6] = "ENUM",
			[7] = "INT_LIST",
			[8] = "ENUM_LIST",
			[9] = "ENUM_DICT",
		},
		["DESTROY_TYPE"] = {
			"DESTROY_ON_TIME",
			"FOLLOW_STATE",
			"FOLLOW_ENTITY",
			"FOLLOW_ANIM",
			"FOLLOW_BUFF",
			"DESTROY_ON_EXIT_FIGHT",
			[0] = "NONE",
		},
		["DIE_TYPE"] = {
			"STAND_DIE",
			"LIE_DIE",
			"STAND_BURN_DIE",
			"LIE_BRUN_DIE",
			"STAND_FREEZE_DIE",
			"LIE_FREEZE_DIE",
			"FORCE_REMOVE",
		},
		["DIRECTION"] = {
			"NONE",
			"FRONT",
			"BACK",
			"LEFT",
			"RIGHT",
		},
		["DIRECTION_TAB_TYPE"] = {
			"BACK",
			"LEFT",
			"RIGHT",
			[0] = "FRONT",
		},
		["DISAPPEAR_TYPE"] = {
			"IMMEDIATELY",
			"IGNORE",
			"SOFT_DELETE",
			[0] = "NONE",
		},
		["EDIT_ANIM_STATUS"] = {
			"BIRTH",
			"REVIVE",
			"IDLE",
			"MOVE",
			"ATTACK",
			"HIT",
			"JUMP",
			"RUSH",
			"LIE",
			"AIATTACK",
			"KNIFEBACK",
			"UNBALANCE",
			"DEAD",
			"FORCE",
			"COLLECT",
			[0] = "NULL",
		},
		["EDIT_EQUSINGLE"] = {
			"EQUL",
			"LOWER",
			"BIGEQUL",
			"LOWEQUL",
			[0] = "BIGGER",
		},
		["EDIT_EXIST"] = {
			"EXIST",
			[0] = "NONE",
		},
		["EDIT_SKILL_BTN_NAME"] = {
			"NORMAL_ATK",
			"EVADE_SKILL",
			"SPIRIT_PRESSURE",
			"JUMP",
			"FIRST_SKILL",
			"SECOND_SKILL",
			"THIRD_SKILL",
			[0] = "NULL",
		},
		["EDIT_STATE_ROTATION"] = {
			"TARGET",
			"IGNORE_JOYSTICK",
			"JOYSTICK_SOON",
			"JOYSTICK_TARGET",
			[0] = "NONE",
		},
		["EFFECT_CAMP_TYPE"] = {
			"TEAM",
			"HERO",
			"MONSTER",
		},
		["EFFECT_ROTATION_TYPE"] = {
			"TO_ACTOR",
			"TO_IGNORE",
			"TO_CAMERA",
			"TO_ROTATION",
			[0] = "NONE",
		},
		["ELLIPSE_TYPE"] = {
			"LEFT_ELLIPSE",
			"RIGHT_ELLIPSE",
		},
		["EMITTER_TRIGGER_TYPE"] = {
			"COLLIDE_CHR",
			"COLLIDE_WALL",
			"COLLIDE_GROUND",
			"LIFETIME_END",
			"MOVE_END",
		},
		["EMITTER_TYPE"] = {
			"CIRCLE",
			"RANDOM",
			"CUSTOM",
		},
		["FACETPYE"] = {
			"SELF",
			"ENEMY",
			"INHERIT_BULLET",
			"INHERIT_EMITTER",
		},
		["FIRE_TYPE"] = {
			"ACTIVE",
			"PASSIVE",
		},
		["FLY_TRACK_TYPE"] = {
			"LINE",
			"STAY",
			"PARABOLA",
			"STAY_ON_LAND",
			"ATTACH",
			"ATTACH_TARGET",
			"LOCK_TARGET_PARABOLA",
			"TORNADO",
			"LINE_BOOMERANG",
			"STAY_ROTATION",
			"ACCELERATION_LINE",
			"GUIDANCE",
			"FOLLOW",
		},
		["FRAME_EVENT_TYPE"] = {
			"CUSTOM_EVENT",
			"BOX_EVENT",
			"EFFECT_EVENT",
			"SPEED_EVENT",
			"DISSOLVE_EVENT",
			"WWISE_EVENT",
			"ANIM_EVENT",
			"BLEND_TREE_ANIM_EVENT",
			"1D_BLEND_TREE_ANIM_EVENT",
			"BULLET_EVENT",
			"AI_CAN_MOVE_EVENT",
			"AI_CAN_SET_STATE_EVENT",
		},
		["FRAME_EVENT_VAILD_TYPE"] = {
			"CAPTURE_MAIN_PLAYER",
			[0] = "NONE",
		},
		["HERO_ABSTRACT_STATE_TYPE"] = {
			[10000] = "HERO_IDLE",
			[10001] = "HERO_SKILL1",
			[10002] = "HERO_SKILL2",
			[10003] = "HERO_SKILL3",
			[10004] = "HERO_SKILL_IN",
			[10005] = "HERO_SKILL_OUT",
			[10006] = "HERO_SKILL_QTE",
			[10007] = "HERO_SKILL_DODGE",
			[10008] = "HERO_MOVE",
		},
		["HIT_BY_TYPE"] = {
			[10001] = "HARD_HURT",
			[10002] = "LIE_HURT",
			[10003] = "NOT_ACTION_HURT",
		},
		["HIT_RESULT_TYPE"] = {
			"HURT_PENETRATE",
			"HURT_DISAPPEAR",
			"DISAPPEAR",
			"HURT_NUM_DISAPPEAR",
			[0] = "IGNORE",
		},
		["HIT_STATE_TYPE"] = {
			"MIDDLE",
			"RIGHT",
			"AFTER",
			"RANDOM",
			[0] = "LEFT",
		},
		["HIT_TYPE"] = {
			"MELEE",
			"RANGED",
			"CHARGE",
		},
		["INTERRUPT_TAB_TYPE"] = {
			"STATE_PLAYEND",
		},
		["KNIFE_TYPE"] = {
			"PARRY",
			[0] = "BE_PARRY",
		},
		["LOGIC_TYPE"] = {
			["combat/camera/cameraArt"] = "ART",
			["combat/camera/cameraArtCombat"] = "NORMAL",
		},
		["MOVE_TYPE"] = {
			"LOADING_MOVE",
			"LOCK_MOVE",
			"FACE_MOVE",
			"OBLIQUE_MOVE",
		},
		["OBJ_ATTR"] = {
			"Atk",
			"Def",
			"WalkSpeed",
			"Op",
			"UltEnergy",
			"Sp",
			"SpeEnergy",
			"TeamEnergy",
			"DodgeEnergy",
			"SkillBtnClickTime",
			[0] = "Hp",
		},
		["PRODUCEOTHERTYPE"] = {
			"EMITTER_OVER",
			"BULLET_BREAK_OVER",
			"BULLET_HIT",
			"BULLER_COLLIDER_END",
			"BULLET_COLLIDER_DISAPEAR",
			"LASR_MOUTH_LIFE_END",
			"BULLET_LIVE",
			[0] = "NONE",
		},
		["ROLE_TYPE"] = {
			"HERO",
			"HERO_MAINCITY",
			"MONSTER",
			"WEAPON",
			[0] = "NONE",
		},
		["ROTATION_TYPE"] = {
			"TARGET",
			[0] = "INPUT",
		},
		["RUNSTATE"] = {
			"WALK",
			"RUN",
			"DASH",
			"DASH_TURN",
			[0] = "STOP",
		},
		["RUNTYPE"] = {
			"WALK",
			"RUN",
			"DASH",
		},
		["SHOOTING_DIRTYPE"] = {
			"SECTOR",
			[0] = "PARALLEL",
		},
		["SKILL_BTN_SLOT"] = {
			"DODGE_SLOT",
			"SKILL1_SLOT",
			"SKILL2_SLOT",
			"RELOAD_SLOT",
			"SHOOT_SLOT",
		},
		["SKILL_BTN_TYPE"] = {
			"NORMAL",
			"SKILL1",
			"SKILL2",
			"SWITCH_HERO1",
			"SWITCH_HERO2",
			"DODGE",
			"RELOAD",
			"HERO1_SKILL2",
			"HERO2_SKILL2",
			"SOLDIERS_DUEL",
			[0] = "MOVE",
		},
		["SKILL_JOYSTICK_INPUT_TYPE"] = {
			"ONLY_DIRECTION",
			"DIRECTION_AND_DISTANCE",
			[0] = "NONE",
		},
		["SKILL_JOYSTICK_TYPE"] = {
			"STRAIGHT",
			"CYCLE",
			"PIN_POINT",
			"FAN",
			[0] = "NONE",
		},
		["SKILL_TRIGGER_EVENT"] = {
			"HERO_IN",
			"RE_GUNS",
			"DAMAGE_FRONT",
			"DAMAGE_AFTER",
			"GET_DAMAGE_FRONT",
			"GET_DAMAGE_AFTER",
			"USE_HERO_SKILL",
			"DODGE_SUCCESS",
			"KILL_CHARACTER",
			"RE_BULLETS",
			[0] = "NONE",
		},
		["SKILL_TYPE"] = {
			"HERO_SKILL",
			"MECHANISM_SKILL",
			"HERO_TACTICAL_SKILL",
			"MOVEMENT_SKILL",
			"WEAPON_STAR_SKILL",
			"WEAPON_BREAK_SKILL",
			"VEHICLE_PASSIVE_SKILL",
			"VEHICLE_UPGRADE_PASSIVE_SKILL",
			"SOLDIERS_DUEL",
			"GEM_SKILL",
		},
		["SOUND_TYPE"] = {
			"NORMAL",
			"HURT",
			"UI",
			"BGM",
			"SKILL",
			"DIALOG",
			"ANIMATION",
			"INTRO",
			"RESULT",
			"PPT",
			"MOVE",
			"ENDING",
			"FORMATION",
			"OP",
			[0] = "NONE",
		},
		["STATE_GUIDE_FX"] = {
			"BUTTERFLY",
			"RING",
		},
		["STATE_HEIGHT_TYPE"] = {
			"STAND",
			"LIE",
		},
		["STATE_LIMIT_TYPE"] = {
			"USE_ANIM_OFFSET",
			"CAN_MOVE",
			"CAN_TURN_AROUND",
			"LIMIT_AI",
			"CAN_HIT",
			"USE_ANIM_CURVE",
			"CHECK_SWITCH_HERO",
			"ENABLE_IK",
			"ENABLE_DODGE_FACE",
			"CAN_T_DIE",
			"LIMIT_SHAKEBONE",
			"HEAD_LOOK_AT",
			"LIMIT_HIT_PROTECT",
			"CAMERA_STATE",
			"LIMIT_AID_SKILL",
			"NOT_BE_PUSH",
			"NOT_PUSH",
			"NOT_BULLET_TIME",
		},
		["STATE_TYPE"] = {
			"BORN",
			"REVIVE",
			"IDLE",
			"MOVE",
			"SKILL",
			"HIT",
			"JUMP",
			"RUSH",
			"LIE",
			"AIATTACK",
			"KNIFEBACK",
			"UNBALANCE",
			"DEAD",
			"FORCE",
			"COLLECT",
			[0] = "DEFAULT",
		},
		["STOP_TYPE"] = {
			"STOP_ON_SKILL_BREAK",
			"STOP_FORCE",
			[0] = "NONE",
		},
		["TARGET_SECOND_TYPE"] = {
			"MAX_DISTANCE",
			"MIN_HP",
			"MAP_HP",
			"RANDOM",
			[0] = "MIN_DISTANCE",
		},
		["TRACK_TYPE"] = {
			"CUSTOM_TRACK",
			"BOX_TRACK",
			"EFFECT_TRACK",
			"SPEED_TRACK",
			"DISSOLVE_TRACK",
			"WWISE_TRACK",
			"ANIM_TRACK",
			"BLEND_TREE_ANIM_TRACK",
			"1D_BLEND_TREE_ANIM_TRACK",
			"BULLET_TRACK",
			"AI_CAN_MOVE_TRACK",
			"AI_CAN_SET_STATE_TRACK",
			"BULLET_LIFETIME_TRACK",
		},
		["TRIGGER_EFFECTIVE_TYPE"] = {
			"NORMAL",
			"ELITE",
			"BOSS",
			"ENTOURAGE",
			[0] = "NONE",
		},
		["USE_TYPE"] = {
			"SHOW",
			"LOGIC",
			"ALL",
		},
		["VALUE_TYPE"] = {
			"BOOL",
			"INT",
			"FLOAT",
			"TABLE",
		},
		["WEAP_ABSTRACT_STATE_TYPE"] = {
			[11001] = "WEAP_SKILL1",
			[11002] = "WEAP_RELOAD",
		},
	},
	["ENUM_TYPE_EN2CN"] = {
		["1D_BLEND_TREE_ANI_DIR_TYPE"] = "1DBlendTree动画方向类型",
		["1D_BLEND_TREE_ANI_TYPE"] = "1DBlendTree动画类型",
		["1D_BLEND_TREE_PARAM_TYPE"] = "1DBlendTree参数类型",
		["1D_BLEND_TREE_TYPE"] = "1DBlendTree名",
		["ACTION_FREQUENCY"] = "动作出现频率",
		["ADHERE_TYPE"] = "附着类型",
		["AI_CDT_TYPE"] = "AI条件类型",
		["AI_MOVE_CDT_TYPE"] = "AI移动条件",
		["AI_MOVE_TYPE"] = "AI移动类型",
		["AI_OPERATE"] = "AI操作类型",
		["ASSIGN_OPERATE"] = "赋值运算符",
		["ATK_DIR"] = "攻击方向",
		["ATTACK_BOX_TYPE"] = "盒子类型",
		["BF_STOP_TYPE"] = "顿帧对象类型",
		["BLEND_TREE_ANI_DIR_TYPE"] = "BlendTree动画方向类型",
		["BLEND_TREE_ANI_TYPE"] = "BlendTree动画类型",
		["BLEND_TREE_MASK_TYPE"] = "BlendTreeMask名",
		["BLEND_TREE_PARAM_TYPE"] = "BlendTree参数类型",
		["BLEND_TREE_TYPE"] = "BlendTree名",
		["BOX_HIT_TYPE"] = "攻击盒受击类型",
		["BOX_SHAPE_TYPE"] = "盒子形状",
		["BOX_TAB_TYPE"] = "盒子额外分页",
		["BTN_CTRL_TYPE"] = "按键操作类型",
		["BUFF_REPLACE_TYPE"] = "buff覆盖类型",
		["BULLET_CAMP_TYPE"] = "子弹阵营类型",
		["BULLET_FILTER_TYPE"] = "子弹筛选类型",
		["BULLET_FLY_TYPE"] = "子弹轨迹类型",
		["BULLET_POSITION_TYPE"] = "子弹位置类型",
		["CAMERA_BLEND_STYLE"] = "镜头混合曲线类型",
		["CAMERA_LAYER_TYPE"] = "摄像机渲染Layer",
		["CAMP"] = "阵营",
		["COMPARE_OPERATE"] = "比较运算符",
		["DAMAGE_BOX_SUBTYPE"] = "破坏盒子类型",
		["DATA_INPUT_TYPE"] = "数据编辑类型",
		["DESTROY_TYPE"] = "镜头销毁类型",
		["DIE_TYPE"] = "死亡类型",
		["DIRECTION"] = "方向",
		["DIRECTION_TAB_TYPE"] = "方向类型",
		["DISAPPEAR_TYPE"] = "消失类型",
		["EDIT_ANIM_STATUS"] = "动作状态类型",
		["EDIT_EQUSINGLE"] = "大小类型",
		["EDIT_EXIST"] = "存在类型",
		["EDIT_SKILL_BTN_NAME"] = "输入指令类型",
		["EDIT_STATE_ROTATION"] = "状态转向",
		["EFFECT_CAMP_TYPE"] = "特效隐藏阵营类型",
		["EFFECT_ROTATION_TYPE"] = "特效旋转类型",
		["ELLIPSE_TYPE"] = "圆弧类型类型",
		["EMITTER_TRIGGER_TYPE"] = "子弹触发类型",
		["EMITTER_TYPE"] = "发射器类型",
		["FACETPYE"] = "目标类型",
		["FIRE_TYPE"] = "施放类型",
		["FLY_TRACK_TYPE"] = "飞行轨迹类型",
		["FRAME_EVENT_TYPE"] = "动作事件类型",
		["FRAME_EVENT_VAILD_TYPE"] = "帧事件生效类型",
		["HERO_ABSTRACT_STATE_TYPE"] = "英雄抽象状态",
		["HIT_BY_TYPE"] = "受击类型",
		["HIT_RESULT_TYPE"] = "伤害结果",
		["HIT_STATE_TYPE"] = "受击状态类型",
		["HIT_TYPE"] = "攻击类型",
		["INTERRUPT_TAB_TYPE"] = "中断标签条件类型",
		["KNIFE_TYPE"] = "弹刀类型",
		["LOGIC_TYPE"] = "镜头类型",
		["MOVE_TYPE"] = "移动类型",
		["OBJ_ATTR"] = "对象属性",
		["PRODUCEOTHERTYPE"] = "产生其他的发射器的类型",
		["ROLE_TYPE"] = "角色类型",
		["ROTATION_TYPE"] = "转向类型",
		["RUNSTATE"] = "身体状态类型",
		["RUNTYPE"] = "角色表现状态类型",
		["SHOOTING_DIRTYPE"] = "射击方向类型",
		["SKILL_BTN_SLOT"] = "按键槽位",
		["SKILL_BTN_TYPE"] = "按键类型",
		["SKILL_JOYSTICK_INPUT_TYPE"] = "摇杆输入类型",
		["SKILL_JOYSTICK_TYPE"] = "按键摇杆类型",
		["SKILL_TRIGGER_EVENT"] = "技能触发器时机",
		["SKILL_TYPE"] = "技能类型",
		["SOUND_TYPE"] = "音效类型",
		["STATE_GUIDE_FX"] = "关卡指引目标点特效",
		["STATE_HEIGHT_TYPE"] = "状态高度类型",
		["STATE_LIMIT_TYPE"] = "状态机限制类型",
		["STATE_TYPE"] = "状态类型",
		["STOP_TYPE"] = "打断类型",
		["TARGET_SECOND_TYPE"] = "子弹跟踪选择目标小类型",
		["TRACK_TYPE"] = "轨道类型",
		["TRIGGER_EFFECTIVE_TYPE"] = "被动生效类型",
		["USE_TYPE"] = "使用类型",
		["VALUE_TYPE"] = "值类型",
		["WEAP_ABSTRACT_STATE_TYPE"] = "武器抽象状态",
	},
}